### ISSUE TITLE
3.11.0: Compilation fails with gcc 7.2.0

### ISSUE THREAD

**Issue by SpaceIm** [skypjack/entt#951] opened 2022-11-11 10:41 UTC
I've tried to add entt 3.11.0 in conan-center, but simple test example of this recipe (https://github.com/conan-io/conan-center-index/blob/8a0759d8bebc68118a3968437d9ab75ec166cc50/recipes/entt/3.x.x/test_package/test_package.cpp) fails to compile with gcc 7:

```
----Running------
> cmake --build "/home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/entt/3.x.x/test_package/build/Release" '--' '-j3'
-----------------
Scanning dependencies of target test_package
[ 50%] Building CXX object CMakeFiles/test_package.dir/test_package.cpp.o
CMakeFiles/test_package.dir/build.make:81: recipe for target 'CMakeFiles/test_package.dir/test_package.cpp.o' failed
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/test_package.dir/all' failed
Makefile:102: recipe for target 'all' failed
In file included from /home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/container.hpp:17:0,
                 from /home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/entt.hpp:41,
                 from /home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/entt/3.x.x/test_package/test_package.cpp:1:
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/meta.hpp: In constructor â€˜constexpr entt::meta_sequence_container::meta_iterator::meta_iterator()â€™:
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/meta.hpp:1619:21: error: temporary of non-literal type â€˜entt::basic_any<>â€™ in a constant expression
           handle{} {}
                     ^
In file included from /home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/entt.hpp:8:0,
                 from /home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/entt/3.x.x/test_package/test_package.cpp:1:
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/any.hpp:52:7: note: â€˜entt::basic_any<>â€™ is not literal because:
 class basic_any {
       ^~~~~~~~~
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/any.hpp:52:7: note:   â€˜entt::basic_any<>â€™ has a non-trivial destructor
In file included from /home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/container.hpp:17:0,
                 from /home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/entt.hpp:41,
                 from /home/conan/w/prod/BuildSingleReference/conan-center-index/recipes/entt/3.x.x/test_package/test_package.cpp:1:
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/meta.hpp: In constructor â€˜constexpr entt::meta_associative_container::meta_iterator::meta_iterator()â€™:
/home/conan/w/prod/BuildSingleReference/.conan/data/entt/3.11.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/meta/meta.hpp:1713:21: error: temporary of non-literal type â€˜entt::basic_any<>â€™ in a constant expression
           handle{} {}
                     ^
make[2]: *** [CMakeFiles/test_package.dir/test_package.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
make: *** [all] Error 2
```

https://c3i.jfrog.io/c3i/misc/logs/pr/14151/2-linux-gcc/entt/3.11.0//5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9-test.txt

**Comment by skypjack** [comment] 2022-11-11 11:21
🤔 
What version of GCC is it?
The only one I've available on GH [works fine](https://github.com/skypjack/entt/actions/runs/3427721833/jobs/5711071693) with `master` actually.
I can't really reproduce your issue to be honest. Can you help with that?

**Comment by SpaceIm** [comment] 2022-11-11 11:27
It's GCC 7.2.0 in CI of conan-center:

```
-- The CXX compiler identification is GNU 7.2.0
```

**Comment by skypjack** [comment] 2022-11-11 11:31
Well, that's a compiler bug for a version that is dated August 2017 and I can't even test easily.
It ain't easy to get a fix upstream I guess, unless you've a good suggestion in this sense already. 😅

**Comment by SpaceIm** [comment] 2022-11-11 11:49
I can't test easily myself, I don't have control over CI configuration of conan-center. I can ask to conan maintainers to upgrade their linux-gcc7 image.

**Comment by SpaceIm** [comment] 2022-11-11 11:59
Maybe this bug fixed in GCC 7.4: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82461

**Comment by skypjack** [comment] 2022-11-11 13:37
It's very likely that the fix on the `EnTT` side is to turn this:
```cpp
    constexpr meta_iterator() noexcept
        : ctx{},
          vtable{},
          handle{} {}
```
Into this:
```cpp
    meta_iterator() noexcept
        : ctx{},
          vtable{},
          handle{} {}
```
For both `meta_sequence_container::meta_iterator` and `meta_associative_container::meta_iterator`.
Technically speaking, it's an unnecessary change. However 🤷‍♂️ I don't think it's going to hurt any codebase out there.

**Comment by skypjack** [comment] 2022-11-11 13:39
Main problem is that I've no idea how to test it.
I can create a temporary branch with these changes if you know how to make it run on the conan CI.
This is the best I can offer. Otherwise, I'm afraid this is going to stay.

**Comment by SpaceIm** [comment] 2022-11-11 13:55
I've pushed https://github.com/conan-io/conan-center-index/pull/14151/commits/5d4e371b09a03ff2101d92e25e4789b01e9e94b6, it may take a while.

**Comment by skypjack** [comment] 2022-11-11 13:59
Oh. Cool. 😅 
I live in the past compared to you.
Thank you very much!! 👍

**Comment by skypjack** [comment] 2022-11-14 12:13
From what I see, it fixed the issue. Am I wrong?

**Comment by SpaceIm** [comment] 2022-11-14 12:31
Indeed :+1:

**Comment by skypjack** [comment] 2022-11-14 13:56
What's better then? Since the bug is in the compiler, probably the best bet is to update the conan recipe with a patch file rather than changing the source library? Not sure what the common procedure is in this case with conan nor if they're fine with patch files like this one in general.

**Comment by skypjack** [comment] 2022-11-21 09:26
I see that the patch was merged upstream in Conan. Therefore, I guess we can safely close this issue.
Feel free to reopen it if this isn't the case or to continue the discussion here even as closed if needed. 👍 
Thanks for the help and for the quick turnaround.

**Closed by skypjack** 2022-11-21 09:26 UTC
Labels: triage

**Comment by SpaceIm** [comment] 2022-12-04 14:52
@skypjack yes, I don't see any reason for you to tweak entt to support a workaround for a bug in an old gcc version corrected in this major version. I've asked to conan-center maintainers whether they could upgrade their gcc7 minor version.
