### ISSUE TITLE
Using entt::exclude<Component> in a view creates errors in each() under Visual Studio 16.6.1

### ISSUE THREAD

**Issue by kix-mcotton** [skypjack/entt#527] opened 2020-07-19 23:10 UTC
I recently tried to add an exclude filter to an existing, working view iteration and noticed that MSVC would not compile it.
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(756,14): error C2039: '_Ttype': is not a member of 'std::_Tuple_element<_Ty,std::tuple<>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(756,1): error C2061: syntax error: identifier '_Ttype'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(756,14): error C2039: '_Ttype': is not a member of 'std::_Tuple_element<_Ty,std::tuple<entt::storage<Entity,Type,void> *>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(795,68): error C2039: '_Ttype': is not a member of 'std::_Tuple_element<_Ty,std::tuple<entt::storage<Entity,Type,void> *,entt::storage<Entity,ResourceComponent,void> *>>'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(794,78): error C2061: syntax error: identifier '_Ttype'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(794,78): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\include\tuple(796,30): error C2146: syntax error: missing '>' before identifier '_Ttype'
1>    0 Warning(s)
1>    7 Error(s)
```

The code though not exact was basically...
`registry.view<Component1, Component2>(entt::exclude<Component3>).each([&}(entt::entity entity, Component1& comp1, Component2& comp2) {});`
If I simply remove the filter...
`registry.view<Component1, Component2>().each([&}(entt::entity entity, Component1& comp1, Component2& comp2) {});`
It compiles fine.

Currently checked out at master.

**Comment by skypjack** [comment] 2020-07-20 06:11
Uhm. Excluded components are widely used and tested.
I need a minimal, reproducible example to be able to look into your error.
Otherwise I must consider the issue as invalid and close it. I'm sorry.

**Comment by kix-mcotton** [comment] 2020-07-20 14:43
```
struct ComponentA { int x; };
struct ComponentB { int y; };
struct ComponentC { int z; };

void Test(entt::registry& registry)
{
    registry.view<ComponentA, ComponentB>(entt::exclude<ComponentC>).each([](entt::entity entity, ComponentA& a, ComponentB& b) {
        });
}
```
This fails to compile for me with the same error messages posted above. I can remove `.each(...)` and iterate over the view object so it seems something is up with the each method.
Additionally. Removing the exclude filter also compiles.

**Comment by skypjack** [comment] 2020-07-20 15:08
Uhm... [I can't reproduce it](https://godbolt.org/z/qfY7e7) with the last stable release.
Is it a regression? Did you try using v3.4? I've not a VS version at hand at the moment, if you could confirm it would help a lot.
Thanks.

**Comment by kix-mcotton** [comment] 2020-07-21 00:57
So I did some further poking and it seems it must be something with my configuration since I was able to create a completely separate project and try the same code and it appears to compile fine. Perhaps another library I'm including is conflicting with something.

**Comment by kix-mcotton** [comment] 2020-07-21 01:08
Actually scratch that.
So I cleared out a new cpp file so it just looks like so...
```
#include <entt/entt.hpp>

struct ComponentA { int x; };
struct ComponentB { int y; };
struct ComponentC { int z; };

void func(entt::registry& registry) {
    registry.view<ComponentA, ComponentB>(entt::exclude<ComponentC>).each([](entt::entity entity, ComponentA& a, ComponentB& b) {});
}
```
When I include <entt/entt.hpp> I get the error as described. However if I replace the include with <entt/single_include/entt/entt.hpp> it compiles fine.

**Comment by skypjack** [comment] 2020-07-21 11:06
Uhm, ok, it's a recent change apparently. It didn't enter the last release.

**Comment by skypjack** [comment] 2020-07-21 15:03
Please, test branch `experimental` and confirm that the issue is gone.
I confirm that it's a recent change and fortunately it didn't enter a release yet.
Thanks for pointing this out and helping to find it! :+1:

**Comment by kix-mcotton** [comment] 2020-07-21 22:46
Just checked experimental and it looks good to me! Was able to build and exclude components.

**Closed** 2020-07-22 10:08 UTC
Labels: bug
