### ISSUE TITLE
`Storage` doesn't delete itself after emptying it 

### ISSUE THREAD

**Issue by DMitev11** [skypjack/entt#901] opened 2022-06-23 13:22 UTC
Is it an intended behaviour that a `storage`/pool allocated for a class/identifier is created after creating a component of the type, but not deleted after removing the last reference of the component type to an any entity? 

I have a small piece of code deleting the `storage` from the `registry`, after the `size` of it is equal to 0, but I am not entirely sure about the behaviour it could have later on during runtime

_Originally posted by @DMitev11 in https://github.com/skypjack/entt/issues/900#issuecomment-1164393279_

**Comment by Innokentiy-Alaytsev** [comment] 2022-06-23 13:56
Yes, it is the intended behaviour. This way some memory allocations are saved when you create new components of the same type, as the memory allocated previously is reused.

**Comment by DMitev11** [comment] 2022-06-23 16:22
I see, seems like a valid strategy.
Is there a way to delete the `storage`/`pool`, which does not include manually finding the pool and calling manually the `delete` operator? All of that would occur only when it is sure that certain components would not occur again for significant time, and would be cost-worthy to save memory?

**Comment by skypjack** [comment] 2022-06-23 19:07
Swapping it with an empty one? It should work, a storage class doesn't allocate until you put an element into it.

**Comment by skypjack** [comment] 2022-06-29 05:49
The issue is starving. I assume it was answered though. I'll close it in a couple of days if no other comments show up. Thanks.

**Closed** 2022-07-03 10:04 UTC
Labels: question, solved
