### ISSUE TITLE
Warnings for x86 build

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#122] opened 2018-08-04 16:42 UTC
Building the following under x86
```
	entt::DefaultRegistry registry;
	auto view = registry.view<World>();
	for (auto e : view) {}
```
produces warnings in VS2017
```
entt\entity\sparse_set.hpp(153): warning C4244: 'argument': conversion from '__int64' to 'const unsigned int', possible loss of data
entt\entity\sparse_set.hpp(152): note: while compiling class template member function 'const unsigned int *entt::SparseSet<Entity>::Iterator::operator ->(void) noexcept const'
        with
        [
            Entity=uint32_t
        ]
entt\entity\view.hpp(544): note: see reference to function template instantiation 'const unsigned int *entt::SparseSet<Entity>::Iterator::operator ->(void) noexcept const' being compiled
        with
        [
            Entity=uint32_t
        ]
entt\entity\view.hpp(515): note: see reference to class template instantiation 'entt::SparseSet<Entity>::Iterator' being compiled
        with
        [
            Entity=uint32_t
        ]
main.cpp: note: see reference to class template instantiation 'entt::View<Entity,World,Sprite>::Iterator' being compiled
        with
        [
            Entity=uint32_t
        ]
```

**Comment by skypjack** [comment] 2018-08-04 17:59
Cannot reproduce on appveyor with VS2017 - https://ci.appveyor.com/project/skypjack/entt

Can you suggest changes to reproduce it?

**Comment by huwpascoe** [comment] 2018-08-04 20:48
Default warning level for VS2017 C++ projects is /W3, that might show up?

**Comment by skypjack** [comment] 2018-08-04 20:52
Not sure what appveyor consider as a default. Added explicitly /W3 and let's see if it shows up.

**Comment by skypjack** [comment] 2018-08-04 21:27
Oh, ok, it's all about indexing, you can safely ignore them. It uses signed types as indexes and those values are converted to an unsigned type (ie `std::vector<T>::size_type`).

**Comment by skypjack** [comment] 2018-08-05 06:34
Some other warnings are due to the fact that the tests of `EnTT` use `std::uint64_t` as an entity type while `std::size_t` cannot accommodate it. In this case, well, everything works fine as long as you don't use more than 1M entities, but I'd rather pick up a different type so as to avoid errors at runtime if create an outstanding number of entities.

**Comment by skypjack** [comment] 2018-08-05 13:35
I confirm that it is all about indexing and checked conversions. Won't fix.

**Closed by skypjack** 2018-08-05 13:35 UTC
Labels: invalid, wontfix
