### ISSUE TITLE
About monostate

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#904] opened 2022-06-28 09:32 UTC
How can I use monostate with std::string as key just like this? I'm using entt 3.10.1. Thanks a lot!
```cpp
std::string str;
entt::monostate<entt::hashed_string{str}>{} = 3; // This won't compile
```

**Comment by Innokentiy-Alaytsev** [comment] 2022-06-28 10:38
The value you pass as an argument to the template should be compile-time constant. Doing this with runtime strings won't work.

**Comment by skypjack** [comment] 2022-06-28 14:20
Yeah, not sure what the question is. You're trying to pass a runtime value as a template parameter. This doesn't work in C++.
If a compile-time string is fine, you can use it with the built-in hashed string as `monostate<"foo"_hs>{} = 3`. Otherwise, what you're looking for is likely a map?

**Comment by skypjack** [comment] 2022-07-03 10:05
The issue is starving. I'll close it in a couple of days if no other comments show up. Thanks.

**Comment by hls333555** [comment] 2022-07-05 12:34
> Yeah, not sure what the question is. You're trying to pass a runtime value as a template parameter. This doesn't work in C++. If a compile-time string is fine, you can use it with the built-in hashed string as `monostate<"foo"_hs>{} = 3`. Otherwise, what you're looking for is likely a map?

Sorry for the late reply. I thought I could use this to create a console command system. But that seems not possible for compile time. Probably I should change to map. Thanks!

**Closed** 2022-07-05 13:28 UTC
Labels: triage
