### ISSUE TITLE
compiler warnings with g++ 9.3.0 on windows

### ISSUE THREAD

**Issue by roboticarm2000** [skypjack/entt#461] opened 2020-04-11 06:00 UTC
While compiling this test code with g++ 9.3.0 mingw

```c++
int main()
{
  std::vector<Coordinate> x;
  x.push_back(Coordinate({1,2,3}));
  x.push_back(Coordinate({4,3,6}));

  entt::registry registry;
  for (std::size_t i=0;i<x.size();++i) {
    entt::entity entity = registry.create();
    registry.emplace<Coordinate>(entity,x[i]);
  }

  auto view = registry.view<Coordinate>();

  for (auto entity: view) {
    auto& position = view.get<Coordinate>(entity);
    std::cout << position << std::endl;
  }
}
```

I received the following warnings:

g++ test.cpp -g -std=c++17 -I d:/documents/development/ -I d:/documents/development/entt
In file included from test.cpp:3:
d:/documents/development/entt/entt.hpp: In instantiation of 'decltype(auto) entt::basic_registry< <template-parameter-1-1> >::pool_handler<Component>::emplace(entt::basic_registry< <template-parameter-1-1> >&, Entity, Args&& ...) [with Args = {Coordinate&}; Component = Coordinate; Entity = entt::entity]':
d:/documents/development/entt/entt.hpp:8087:86:   required from 'decltype(auto) entt::basic_registry< <template-parameter-1-1> >::emplace(entt::basic_registry< <template-parameter-1-1> >::entity_type, Args&& ...) [with Component = Coordinate; Args = {Coordinate&}; Entity = entt::entity; entt::basic_registry< <template-parameter-1-1> >::entity_type = entt::entity]'
test.cpp:30:45:   required from here
d:/documents/development/entt/entt.hpp:7562:13: warning: 'void entt::storage<Entity, Type, <template-parameter-1-3> >::construct(entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type, Args&& ...) [with Args = {Coordinate&}; Entity = entt::entity; Type = Coordinate; <template-parameter-1-3> = void; entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type = entt::entity]' is deprecated: use ::emplace instead [-Wdeprecated-declarations]
 7562 |             this->construct(entt, std::forward<Args>(args)...);
      |             ^~~~
d:/documents/development/entt/entt.hpp:4436:10: note: declared here
 4436 |     void construct(const entity_type entt, Args &&... args) {
      |          ^~~~~~~~~
d:/documents/development/entt/entt.hpp: In instantiation of 'void entt::storage<Entity, Type, <template-parameter-1-3> >::emplace(entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type, Args&& ...) [with Args = {Coordinate&}; Entity = entt::entity; Type = Coordinate; <template-parameter-1-3> = void; entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type = entt::entity]':
d:/documents/development/entt/entt.hpp:4437:7:   required from 'void entt::storage<Entity, Type, <template-parameter-1-3> >::construct(entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type, Args&& ...) [with Args = {Coordinate&}; Entity = entt::entity; Type = Coordinate; <template-parameter-1-3> = void; entt::storage<Entity, Type, <template-parameter-1-3> >::entity_type = entt::entity]'
d:/documents/development/entt/entt.hpp:7562:13:   required from 'decltype(auto) entt::basic_registry< <template-parameter-1-1> >::pool_handler<Component>::emplace(entt::basic_registry< <template-parameter-1-1> >&, Entity, Args&& ...) [with Args = {Coordinate&}; Component = Coordinate; Entity = entt::entity]'
d:/documents/development/entt/entt.hpp:8087:86:   required from 'decltype(auto) entt::basic_registry< <template-parameter-1-1> >::emplace(entt::basic_registry< <template-parameter-1-1> >::entity_type, Args&& ...) [with Component = Coordinate; Args = {Coordinate&}; Entity = entt::entity; entt::basic_registry< <template-parameter-1-1> >::entity_type = entt::entity]'
test.cpp:30:45:   required from here
d:/documents/development/entt/entt.hpp:4430:35: warning: 'void entt::sparse_set<Entity>::construct(entt::sparse_set<Entity>::entity_type) [with Entity = entt::entity; entt::sparse_set<Entity>::entity_type = entt::entity]' is deprecated: use ::emplace instead [-Wdeprecated-declarations]
 4430 |         underlying_type::construct(entt);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
d:/documents/development/entt/entt.hpp:3854:10: note: declared here
 3854 |     void construct(const entity_type entt) {
      |          ^~~~~~~

It seems the warning is generated from the entt code itself.

**Comment by skypjack** [comment] 2020-04-11 16:07
Is this from `master` or another commit?

**Comment by roboticarm2000** [comment] 2020-04-11 16:30
From the master, I copied the code by clicking on the clone or download button from https://github.com/skypjack/entt/

I'm including the single header entt.hpp 

I'm using MSYS MinGW 32-bit
$ g++ --version
g++.exe (Rev2, Built by MSYS2 project) 9.3.0

**Comment by skypjack** [comment] 2020-04-11 16:35
Yeah, sorry. I closed the laptop and realized that I tried `experimental` rather than `master`.
I'll give it a try as soon as possible and let you know. Sorry for the noise. :+1: 
If it's already fixed on `experimental`, then it's a matter of having it merged on `master` and this should happen soon. :wink:

**Comment by skypjack** [comment] 2020-04-13 16:55
Confirmed. This isn't reproducible on `master`.
It triggers the warning with the last version of the single include file though.
Since I'm updating `master` today or tomorrow, may I ask you to make another test in a couple of days?
Thanks.

**Comment by skypjack** [comment] 2020-04-13 22:28
Upstream. It would be great if you could test `master`. Thanks. I cannot reproduce the error.

**Comment by roboticarm2000** [comment] 2020-04-14 04:35
It seems that g++ 9.3.0 compiles with -Wdeprecated-declarations by default.  Compiling with -Wno-deprecated-declarations is one way to remove the warnings.

I downloaded the code today but didn't notice any changes in the single_include content. Should I wait a couple of days?  

After looking at the warnings a little deeper, there is really two warnings.  

1) in void entt::sparse_set<Entity>::construct(entt::sparse_set<Entity>::entity_type) 
the warning suggests that this call is deprecated 
underlying_type::construct(entt);

I replaced underlying_type::construct(entt) call to underlying_type::emplace(entt) in lines 4430 and 4802 and that seems to get rid of this warning

2) void entt::storage<Entity, Type, <template-parameter-1-3> >::construct(entt::storage<Entity, Type, 
<template-parameter-1-3> >::entity_type, Args&& ...)
the warning suggest to replace the construct call with use emplace

This seems to originate in basic_registry::pool_handler::emplace(...). (line 7562) This function calls this->construct(entt,... (line 4809) which is marked as deprecated.  But just replacing construct with emplace here gives me a compilation error.

Hope this information is helpful.

**Comment by skypjack** [comment] 2020-04-14 06:09
Ok, so you aren't using `master`. You're using the single include file from `master`.
As I said, yes, it contains code that triggers the warning. I've not updated it yet.
All the changes you mentioned have been already applied to the codebase instead.

**Closed** 2020-04-17 21:07 UTC
Labels: triage
