### ISSUE TITLE
parentheses warning I can't figure out

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#226] opened 2019-04-26 20:42 UTC
```
/home/pgruenbacher/Code/cpp/entsim/thirdparty/entt/src/entt/entity/registry.hpp:168:67: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
                         && !((!std::is_same_v<Exclude, Component> && reg.pool<Exclude>()->has(entt)) || ...))
```
but the code in registry.hpp looks fine when I look at it...

**Comment by skypjack** [comment] 2019-04-26 20:45
It seems it gets confused by the pack unrolling. What compiler is it? The CI doesn't show the same warning in any case, but it could be a matter of a flag or so.

**Comment by pgruenbacher** [comment] 2019-04-26 20:46
gcc-8

**Comment by skypjack** [comment] 2019-04-26 20:51
Oh, ok, Travis runs up to GCC 7 actually. This explains why it doesn't return from the CI.  
Btw it seems a wrong warning emitted by the compiler, I'm not that sure how I could suppress it.  
I mean, it's valid code and there already**a lot** of parentheses!! :smile:

**Comment by pgruenbacher** [comment] 2019-04-26 20:55
actually i'm doing gcc 7.3.0 , but i have almost all warnings turned on...
I'll just do -Wno-logical-op-parentheses in my cmake, that gets rid of the warning... 
i really don't get why it's complaining, the parentheses are correct...

**Comment by skypjack** [comment] 2019-04-26 21:00
Well, this isn't the first time I encounter wrong warnings emitted by compilers. The idea is that _more is better_ in this case. A warning isn't an hard error after all and compilers prefer to emit them if in doubts because of bugs or so.

**Comment by pgruenbacher** [comment] 2019-04-26 21:02
correction -Wno-parentheses fixes the warning

**Comment by pgruenbacher** [comment] 2019-04-26 21:03
yea I wouldn't mind as much if there were a way to turn the warning off inline in the code instead of the cmakelists, cause then it wouldn't have to involve globally turning off a valid warning

**Comment by pgruenbacher** [comment] 2019-04-26 21:11
actually this does the trick, i'll reopen for discussion if we want GCC diagnostics littering...

// gcc-7 with -Wall throws an invalid warning regarding parentheses...
#pragma GCC diagnostic ignored "-Wparentheses"
                if((std::get<pool_type<Owned> *>(cpools)->has(entt) && ...)
                        && (reg.pool<Get>()->has(entt) && ...)
                        && !((!std::is_same_v<Exclude, Component> && reg.pool<Exclude>()->has(entt)) || ...))
                {
                    construct();
                }
#pragma GCC diagnostic pop

**Comment by pgruenbacher** [comment] 2019-04-26 21:16
this code is only throwing warnings when entt::exclude<> has more than two types in it when building a group I think, due to a if constexpr wrapping this code... but all the travis tests have only excludes of one type, so that may also be the reason for no warnings by travis...

**Comment by skypjack** [comment] 2019-04-26 21:16
Wow, I didn't even know such a pragma existed!!  
Is it ignored by the other compilers? Btw tell me how to get the same warning, what you've enabled, I'm curious to see where it gets wrong now!

**Comment by pgruenbacher** [comment] 2019-04-26 22:49
yea I'll make a PR with a test that will actulally replicate it. we didn't have any unittests for >1 exclude components!

**Comment by skypjack** [comment] 2019-04-27 20:44
Good. I'll look into this when I'm back home. I'm curious to know if there exists a way to suppress the warning other than by using a pragma.  
Thanks for the time spent on it so far. :+1:

**Comment by skypjack** [comment] 2019-04-30 15:53
I'm closing this as a _duplicate_ of #227 - I've just pushed a workaround on branch `experimental` that doesn't make use of pragmas. :+1:  
Thanks for the PR, I've used your test with the CI to reproduce and get rid of the warning.

**Closed by skypjack** 2019-04-30 15:53 UTC
Labels: duplicate
