### ISSUE TITLE
Component Destructor Called Twice

### ISSUE THREAD

**Issue by mignaciolopez** [skypjack/entt#456] opened 2020-04-03 07:18 UTC
Hi,
Basically what the tittle says, maybe is my implementation problem or its a bug or a feature that im not aware of how it works.

I have made a simple program to check this with an output on destructors of components.
```
#include "entt.hpp"
#include <iostream>

class someComponent
{
public:
	someComponent() {printf("Constructor\n");}
	~someComponent() {printf("Destructor\n")}
};
int main()
{
	{
		entt::registry registry;
		entt::entity someEntity;
		someEntity = registry.create();
		registry.emplace<someComponent>(someEntity);
		registry.remove<someComponent>(someEntity);
		registry.emplace<someComponent>(someEntity);
	}

	std::cin.get();
	return 0;
}
```
output:
Constructor
Destructor
Destructor
Constructor
Destructor

**Comment by skypjack** [comment] 2020-04-03 08:31
I tested it [online](https://godbolt.org/z/nyyPBL) and I can't reproduce what you're observing.
Can you help me in order to investigate and give you a proper answer?
As a rule of thumb, you can assume it works as expected. My guess is that there would be tons of people saying that everything is crashing down otherwise. :wink:

**Comment by Kerndog73** [comment] 2020-04-03 08:37
I suspect this is because you're not printing copy and move constructors.

**Comment by mignaciolopez** [comment] 2020-04-03 20:14
ok, try [this one](https://godbolt.org/z/Y_CSfs). whats going on under the hood?

```
#include <https://raw.githubusercontent.com/skypjack/entt/master/single_include/entt/entt.hpp>
#include <iostream>

class Acomp final
{
public:
	Acomp(int data) : _data(data){printf("Acomp Constructor\n");}
	~Acomp() {printf("Acomp Destructor\n");}
	int _data;
};
class Bcomp final
{
public:
	Bcomp(int* data) : _data(data){ printf("Bcomp Constructor\n"); }
	~Bcomp() { printf("Bcomp Destructor\n"); }
	int* _data;
};

int main()
{
	{
		int bdata = 1;
		int* Bptrdata = new int;
		Bptrdata = &bdata;

		entt::registry registry;
		entt::entity someEntity;
		someEntity = registry.create();
		registry.emplace<Acomp>(someEntity, 1);
		registry.remove<Acomp>(someEntity);
		registry.emplace<Bcomp>(someEntity, Bptrdata);
	}
	std::cin.get();
	return 0;
}
```

**Comment by mignaciolopez** [comment] 2020-04-03 20:17
if you debug step by step before the call to
`registry.emplace<Bcomp>(someEntity, Bptrdata);`
AComp got removed twice

**Comment by Innokentiy-Alaytsev** [comment] 2020-04-03 20:20
[Not exactly](https://godbolt.org/z/qBms42). There is an instance that the value is moved from and this instance gets destroyed as well. At least, the way I understand it.

**Comment by skypjack** [comment] 2020-04-03 20:31
Your _issue_ boils down to [this](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L407) function.
The `remove` performs a sort of _swap-and-pop_ between the instance assigned to the entity and the last one in the storage, so as to keep the internal array packed.
To avoid nasty issues with the types from the standard library (I won't go in details to be short), this function has a form that is slightly different from what one would expect but you can approximate it with a _swap_ for what matters here.

That said, as you can see there are two instances of your first type. If that type was moveable (minimum requirement) you would have a proper _half-swap_. Since it's not though, you've literally a copy.
In both cases, the destructor is invoked twice because you've two objects to destroy. There is no issue here.

**Comment by mignaciolopez** [comment] 2020-04-03 20:41
ok, thanks for the help.

**Comment by skypjack** [comment] 2020-04-03 20:53
You're welcome. I invite you to join the gitter channel for this kind of questions. You can often receive more details and get your answer quickly. :wink:

**Comment by skypjack** [comment] 2020-04-04 14:31
I'm closing this as invalid. Let me know if you've still doubts. :+1:

**Closed by skypjack** 2020-04-04 14:31 UTC
Labels: invalid
