### ISSUE TITLE
Unused variables in snapshot.hpp in release mode.

### ISSUE THREAD

**Issue by kix-mcotton** [skypjack/entt#520] opened 2020-07-15 05:04 UTC
I noticed there's a few asserts in the snapshot code that results in unused variables when compiling release versions. I've temporarily resolved it with an UNUSED macro but I thought it might be worth reporting.
Using entt version 3.4.0

**Comment by skypjack** [comment] 2020-07-15 07:52
Thanks for pointing this out. I'll suppress them directly into the library. :+1:

**Comment by skypjack** [comment] 2020-07-15 07:56
May I ask you what are the unused variables you get reported? I can't reproduce this upstream.

**Comment by skypjack** [comment] 2020-07-15 14:14
Oh, wait, is this:
```
ValueIterator itsValueItBegin, itsValueItEnd;
```
Within `json.hpp`? This is from the cereal project, it's not due to `EnTT` and therefore I can't do much for it. I'm sorry.
If you confirm that this is the variable to which you are referring, we can close the issue. Thanks.

**Comment by kix-mcotton** [comment] 2020-07-15 22:09
It was in basic_snapshot_loader
```
template<typename Type, typename Archive, typename... Args>
void assign(Archive &archive, Args... args) const
```
two instances of
`const auto entity = reg->valid(entt) ? entt : reg->create(entt);`

**Comment by skypjack** [comment] 2020-07-16 16:04
Oh, ok, it's already solved upstream on `master`/`experimental`. What version of `EnTT` are you using?

**Comment by kix-mcotton** [comment] 2020-07-16 22:00
Ahh good news.
I'm using 3.4.0

**Comment by skypjack** [comment] 2020-07-16 22:10
Can I ask you to try master and confirm it's gone? I can't reproduce it anymore.

**Comment by kix-mcotton** [comment] 2020-07-16 22:38
Looks good to me.

Additionally while I'm here. I made some local changes to the snapshot code for my use. I changed calls to where you would get/set the size of the next section with `archive(typename traits_type::entity_type(sz));` to a templated version, `archive.template operator()<Component>(typename traits_type::entity_type(sz));`
This was so I knew the type of component about to be serialized out. Just curious if this might be a bad idea or there would be a better way of doing it.

**Comment by skypjack** [comment] 2020-07-16 22:43
:thinking: is this online? Not sure I get what you mean.

**Comment by kix-mcotton** [comment] 2020-07-16 22:55
No it's only locally used currently. But in the component serialization/deserialization where you pass the count to the archive, I needed the type info when writing the type size out so I changed the call to a templated call.
So line 39 on snapshot.hpp was changed to `archive.template operator()<Component>(typename traits_type::entity_type(sz));` in basic_snapshot
and line 172 was changed to `archive.template operator()<Type>(length);` in basic_snapshot_loader

The archive can then use the signature
```
template<typename T>
void operator()(std::underlying_type_t<entt::entity> count) {}
```
And I now have access to do things like entt::type_info<T>() within the call (in my specific case I'm spitting out json info so I can get the name of the component etc.

**Comment by skypjack** [comment] 2020-07-19 09:05
Wouldn't it be enough if I passed the size as-is instead of converting it to `size_t`?
Main problem here is that `size_t` isn't really portable, that's the whole point of the conversion.

**Comment by kix-mcotton** [comment] 2020-07-19 14:38
I'm not changing anything regarding the type of the size.

The problem I'm trying to solve, is that when the snapshot tells me (or the archive) it has N components to write out, I don't know what type of component that is. Only that it is N of some type of component. The change I made turned that operator into a templated function so now I know that the type of the component is T.

For eg. as it is in master right now. Say I have 5 TransformComponents that are to be serialized. I'd get the call to `archive(5)` followed by `archive<TransformComponent>(entity, comp)`
After my change the first call changes to `archive<TransformComponent>(5)` so now I know that the 5 components about to be serialized are TransformComponents. And in my case that means I can fetch a json node "TransformComponents" and spit out the following data into it.

It's also possible I have the wrong idea about how it works. I've only been working on this code for a short while.

**Comment by skypjack** [comment] 2020-07-19 14:47
Oh, ok, I misread it from mobile. I've just realized that you passed the component type and not the _size type_. Sorry.

**Comment by skypjack** [comment] 2020-07-24 09:19
I'm not going to change the invocation the way you proposed, mainly because it can break already existing code. I'm sorry.
On the other hand, I want to update the snapshot part soon (it's in the todo list already) and the new model will probably fit better your requirements.
Stay tuned.

I'm closing the issue since the original problem (unused variables in `snapshot.hpp`) is solved upstream. Thanks for reporting it.

**Closed by skypjack** 2020-07-24 09:19 UTC
Labels: invalid
