### ISSUE TITLE
Intel C++ fails to compile

### ISSUE THREAD

**Issue by franjesus** [skypjack/entt#688] opened 2021-04-07 14:06 UTC
https://github.com/skypjack/entt/blob/10636c82a21a910022a62e39153956669066de39/src/entt/core/family.hpp#L30
that is giving me:
```cpp
/home/user/.conan/data/entt/3.4.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/family.hpp(30): error: expression must have a constant value
      inline static const family_type type = identifier++;
                                             ^
/home/user/.conan/data/entt/3.4.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/family.hpp(30): note: attempt to access run-time storage
      inline static const family_type type = identifier++;
                                                       ^
```
Did anyone have success with Intel compilers in the past?

**Comment by skypjack** [comment] 2021-04-07 14:55
🤔 doesn't it support inline static variables?

**Comment by jamesl-github** [comment] 2021-04-07 15:06
the problem appears to be that the variable is "inline static CONST"  
but it isn't declared with a const value 
its declared with identifier++

**Comment by franjesus** [comment] 2021-04-07 15:09
Just removed the const, but I still get the same:

```cpp
/home/user/.conan/data/entt/3.4.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/family.hpp(30): error: expression must have a constant value
      inline static family_type type = identifier++;
                                       ^
/home/user/.conan/data/entt/3.4.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/core/family.hpp(30): note: attempt to access run-time storage
      inline static family_type type = identifier++;
                                                 ^
```

**Comment by franjesus** [comment] 2021-04-07 15:18
Seems like identifier needs to be compile-time but for "reasons" it identifies it as run-time. Is this UB?

**Comment by skypjack** [comment] 2021-04-07 15:40
I wouldn't say so, it's just the typical C++17 static inline feature with which almost all compilers have problems sooner or later. Dunno why it's so problematic.
There exists a workaround that might work though.

Is there any chance that you can try it with an Intel compiler if I provide you with a snippet to replace this class?
Or... Dunno, if you know how to setup the GH CI for that, it would be fine as well. Any hint?

**Comment by franjesus** [comment] 2021-04-07 16:52
I can quickly try, no problem.

**Comment by skypjack** [comment] 2021-04-07 17:15
Wait a moment. What part of EnTT are you using? Are you trying to compile the tests?
`family.hpp` is only visited if you compile the tests, include `entt.hpp` or use the single include file.
Put aside the first case, if you want to do a quick test you can just include the files that you need and avoid it.

**Comment by franjesus** [comment] 2021-04-08 10:29
That did it for me :) Issue with ICC is still there, but I guess it's "their" issue.

**Comment by skypjack** [comment] 2021-04-08 10:55
Yeah, most likely. However, I've probably found a way to add it as a compiler on the CI.
If I can get it to work, I'll fix the errors and guarantee full compatibility with all modules.
Thanks for pointing this out. 👍

**Comment by franjesus** [comment] 2021-04-08 10:59
Nice, thanks again!

**Comment by skypjack** [comment] 2021-04-10 22:49
I've set up icc on branch `build_system`. It doesn't compile everything yet, but I'll refine it a little at a time.
I don't think I'll suppress all its warnings though. It seems a little overzealous on many aspects.
Since you confirmed that the ECS part works already, I'm closing the issue in the meantime. I suggest to keep an eye on the branch to know when the other parts work as well.
At the moment, it seems to return a (wrong) error from meta, because a static assert in the else clause of an `if constexpr` that isn't satisfied when the other branch is taken. It shouldn't fail in this case, but still. 🤷‍♂️

**Closed by skypjack** 2021-04-10 22:49 UTC
Labels: triage
