### ISSUE TITLE
Error when compiling with MSVC

### ISSUE THREAD

**Issue by gamehacker1999** [skypjack/entt#434] opened 2020-03-03 05:52 UTC
@skypjack Hello,

I am trying to integrate Entt's ECS on top of an existing DX12 Rendering engine. When I try to compile my code, I am getting an error.

`1>D:\users\source\repos\DX12Engine\include\entt\core\type_info.hpp(60,30): error C2131: expression did not evaluate to a constant
1>D:\users\source\repos\DX12Engine\include\entt\core\hashed_string.hpp(77,13): message : a non-constant (sub-)expression was encountered`

Any suggestions on why I might be running into this issue?

**Comment by skypjack** [comment] 2020-03-03 06:35
Hi, what version of MSVC are you using?

**Comment by gamehacker1999** [comment] 2020-03-03 06:44
@skypjack I am using Visual Studio 2019 so version 14.2

**Comment by skypjack** [comment] 2020-03-03 07:01
May I ask you to provide a small, reproducible example? It would help quite a lot to investigate your problem.

**Comment by gamehacker1999** [comment] 2020-03-03 07:15
@skypjack If this helps, just using my custom component anywhere in the code while assigning the component to an entity causes the problem causes the problem. If this didn't help, I could provide a reproducible example.

**Comment by skypjack** [comment] 2020-03-03 07:51
No, it's fine. I guess your types are trivial anyway.
The CI [tests this stuff](https://github.com/skypjack/entt/runs/475942744?check_suite_focus=true#step:3:6) with MSVC 19.24.28316.0, so probably you hit a release of which I didn't know where `__FUNCSIG__` isn't `constexpr`.
What version of MSVC runs behind VS2019 14.2? I've no clue on this, sorry.

In the meantime, if you want to make it work while I'm trying to figure out what's the issue with VS, you can define the macro `ENTT_STANDARD_CPP`.

**Comment by gamehacker1999** [comment] 2020-03-03 08:08
@skypjack I am getting the same error if I define the macro unfortunately

**Comment by skypjack** [comment] 2020-03-03 08:17
:thinking: 
If you set correctly the macro (as in `-DENTT_STANDARD_CPP` with gcc/clang), it doesn't go anymore through the path where you're hitting your problem.
It's unlikely the error is the same. It would mean that it didn't intercept the macro.

Anyway, what version of MSVC runs behind VS2019 14.2?
I cannot reproduce your issue in any case. I tried several versions of VS but none of them fails.

**Comment by Innokentiy-Alaytsev** [comment] 2020-03-03 08:21
What @skypjack wants is `cl.exe` compiler version - there are a lot of different versions with a pattern 19.2* that can hide behind platform toolset 14.2*)

**Comment by gamehacker1999** [comment] 2020-03-03 08:24
If you are asking about MSC_VER then it is 1924

**Comment by skypjack** [comment] 2020-03-03 08:39
Then I cannot reproduce it. Apparently, MSVC 19.24 [has no problems](https://godbolt.org/z/9AFr78) with the following code:
```
struct position {
    float x;
    float y;
};

int main() {
    entt::registry registry;

    for(auto i = 0; i < 10; ++i) {
        auto entity = registry.create();
        registry.assign<position>(entity, i * 1.f, i * 1.f);
    }
}
```
[It works as well](https://godbolt.org/z/fcngvK) when defining `ENTT_STANDARD_CPP` as expected.
I understand from you that it shouldn't compile in both cases instead. Did you set C++17 as default? What configuration are you using with VS?

As it stands right now, I've no idea about the reasons of your issue but it's invalid for me, I'm sorry.
Unless you can provide more details or prove with the online tool that there is an issue (it would be great since this would contain also the code to reproduce it), I don't have evidence of a problem.

**Comment by gamehacker1999** [comment] 2020-03-03 18:10
So, If I remove the constexpr keyword, everything seems to work fine, but I don't know if it's going to cause problems later on.

**Comment by skypjack** [comment] 2020-03-03 18:45
It's going to hurt in the measure in which you start hashing things at runtime, so yes, it may be annoying.
The real problem is that I cannot reproduce your issue with your compiler version though and you cannot provide an example nor the exact version of the buildset. This way it's a bit hard to face and understand what's going on.
Could you help in this sense?

**Comment by skypjack** [comment] 2020-03-06 14:39
We failed in trying to reproduce this issue and I confirm the fact that it is _invalid_.

With the information provided and despite repeated requests for more details, all I can do is to close the issue since at the moment there is no evidence of problems with the specified version of VS.
Feel free to reopen the issue if you can provide all is needed to reproduce the problem. I'll do the same in case I find a proper way to easily reproduce it.
Hopefully, if it's due to a VS update that I don't have yet, it shouldn't take long before I hit the same problem.

**Closed by skypjack** 2020-03-06 14:39 UTC
Labels: invalid

**Comment by shadowndacorner** [comment] 2020-04-13 20:47
I just ran into this issue on a project I'm working on after adding the [/permissive-](https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019) flag.  Removing the flag allows the code to compile.

My understanding is that new projects created in Visual Studio have that flag by default, but generated projects from utilities like CMake, premake, etc don't, so it seems likely to me that the flag is causing this issue.

**Comment by shadowndacorner** [comment] 2020-04-13 21:40
My previous comment was written with MSVC Version 19.24.28314.  I updated to 19.25.28612 and can no longer reproduce, so it seems like a compiler bug with that particular flag in that version.

**Comment by skypjack** [comment] 2020-04-13 21:41
Thanks for reporting @shadowndacorner this will help other users for sure! :+1:
