### ISSUE TITLE
lib_registry_plugin test fails with exception in debug mode

### ISSUE THREAD

**Issue by ElDesalmado** [skypjack/entt#722] opened 2021-06-24 11:25 UTC
MSVC 19.27.29111 x64

With MSVC exception is thrown due to access violation in function `static bool cr_plugin_load_internal(cr_plugin &ctx, bool rollback)` in `cr.h`.

`cr_plugin &ctx` is apparently not initialized.
![image](https://user-images.githubusercontent.com/36333890/123254078-a5517b00-d507-11eb-9ad8-74d27527860d.png)

In Release mode this test passes.

MinGW fails to link test due to unresolved external symbol:
```
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe -g  test/CMakeFiles/odr.dir/odr.cpp.obj test/CMakeFiles/lib_registry_plugin.dir/lib/registry_plugin/main.cpp.obj -o test\lib_registry_plugin.exe -Wl,--out-implib,test\liblib_registry_plugin.dll.a -Wl,--major-image-version,0,--minor-image-version,0  lib/libgtest_maind.a  lib/libgtestd.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/lib_registry_plugin.dir/lib/registry_plugin/main.cpp.obj:C:\dev\repos\entt\cmake-build-debug-mingw-w64/_deps/cr-src/cr.h:1037: undefined reference to `__imp_ImageNtHeader'
```

**Comment by skypjack** [comment] 2021-06-24 14:47
I don't know specifically about msvc 19.27.x but we compile the test in debug with msvc 19.29.x [here](https://github.com/skypjack/entt/runs/2904533940?check_suite_focus=true#step:3:15) and the error doesn't reproduce. Nor it reproduced for the last release, msvc version 19.28.x ([here](https://github.com/skypjack/entt/runs/2330932913#step:4:21)). Similarly, the same test is compiled in debug and executed under the sanitizer [here](https://github.com/skypjack/entt/runs/2904533484?check_suite_focus=true) (in this case it's clang 11) and no errors are reported.
It goes without saying that I've not been able to reproduce it locally. Without more context, it seems to me an invalid issue honestly. I'm sorry.

I can't speak instead about mingw since the error is from `cr` and you should probably report it to [this repo](https://github.com/fungos/cr).
I just use it for some local/remote tests but I don't give any guarantee on its portability nor on the fact that it works with mingw. 🤷‍♂️

**Comment by skypjack** [comment] 2021-07-05 12:37
I assume this has been fixed as I can't reproduce it and the issue has been hanging for more than 10 days.
I close the issue. Feel free to continue the discussion here is the problem persists. Thanks.

**Closed by skypjack** 2021-07-05 12:37 UTC
Labels: triage
