### ISSUE TITLE
What do I do wrong? class destructor called even when I added the class object to entt?

### ISSUE THREAD

**Issue by MariwanJ** [skypjack/entt#1117] opened 2024-02-26 17:23 UTC
I have a problem that after registering a class object component, the class-destructor is called as soon as the addition is made and returned happens from the function? 
I use latest entt. 
Thanks.

**Comment by skypjack** [comment] 2024-02-26 17:32
Can you provide a minimal reproducible example, please?
I barely get what you're talking about, sorry. Thanks in advance.

**Comment by MariwanJ** [comment] 2024-02-26 17:43
I would put the link to the whole project if you want. but it is a little bit work to compile. Difficult to write any code here. If you know Hazel game engine, he made a class that uses entt. 
Inspired by that I made similar class. But I dont use struct. I have for ex. shader class that take mesh object . That shader must be added to entt. But the class destructor is called as soon as it is done with the creation. Here is some code.

 `    void Fr_enttScene::CreateAxis() {
        auto axisItems = createItem("Axis3D_axis");
        auto allAxis = axisItems.addItem<Axis3D>();
        allAxis.CreateAxis3D();
// Destructor is called here
    }`

that is the createItem 
`
Fr_Item Fr_enttScene::createItemWithID(genID id, const std::string& name)
{
    Fr_Item  newItem = { m_Registry.create(), this };
    newItem.addItem<ItemID>(id);
    newItem.addItem<Transform>();
    auto& tempname = newItem.addItem<ItemName>();
    tempname.m_Name = name.empty() ? "Item" : name;
    m_ItemMap[id] = newItem;
    return newItem;
}

Fr_Item Fr_enttScene::createItem(const std::string& name)
{
    return createItemWithID(genID(), name);
}
`

`
 class FRTK_API Fr_Item
 {
 public:
     Fr_Item() = default;
     Fr_Item(entt::entity IDval, Fr_enttScene* Scene_val);
     Fr_Item(const Fr_Item& other) = default;

     template<typename T, typename... Args>
     T& addItem(Args&&... args)
     {
         T& component = m_enttScene->m_Registry.emplace<T>(m_ID, std::forward<Args>(args)...);
         return component;
     }

     //template<typename T>
     //T addOrReplaceSharedItem(T item) {
     //   T comp = m_enttScene->m_Registry.emplace_or_replace<T>(m_ID, item);
     //   return comp;
     //}

     template<typename T, typename... Args>
     T& addOrReplaceItem(Args&&... args)
     {
         T& component = m_enttScene->m_Registry.emplace_or_replace<T>(m_ID, std::forward<Args>(args)...);
         return component;
     }

     template<typename T>
     T& GetItem()
     {
         return m_enttScene->m_Registry.get<T>(m_ID);
     }

     template<typename T>
     bool HasItem()
     {
         return m_enttScene->m_Registry.has<T>(m_ID);
     }

     template<typename T>
     void delItem()
     {
         m_enttScene->m_Registry.remove<T>(m_ID);
     }

     operator bool() const { return m_ID != entt::null; }
     operator entt::entity() const { return m_ID; }
     operator uint32_t() const { return (uint32_t)m_ID; }

     genID GetUUID() { return GetItem<ItemID>().ID; }
     const std::string& GetName() { return GetItem<ItemName>().m_Name; }

     bool operator==(const Fr_Item& val) const
     {
         return m_ID == val.m_ID && m_enttScene == val.m_enttScene;
     }

     bool operator!=(const Fr_Item& other) const
     {
         return !(*this == other);
     }
 private:

     entt::entity m_ID{ entt::null };
     Fr_enttScene* m_enttScene = nullptr;
 };
`

**Comment by skypjack** [comment] 2024-02-27 18:16
Really, I don't get what you mean with _the class destructor is called as soon as it is done with the creation_ and I can't compile and debug random projects from the web during the day, you know. 🙂 
What destructor is called? The one of your component? What does _after creation_ mean? Perhaps after invoking `emplace`?

**Comment by MariwanJ** [comment] 2024-02-27 19:18
Nothing is holding the calss. I even debugged and searched for the object, I cannot find their tag or name inside the entt objects (Registery). The destructor of the Grid class (mesh) is called even if it is added using the code mentioned above. 
Don't know why the object added is not there. It is difficult for me to explain my code which is quite huge. I might make a video of that if you want. 
I tried even the CreateAxis class which is the axises (xyz) in different coloers. They also get the same thing. Destructor called after the CreateAxis function finish.

**Comment by skypjack** [comment] 2024-03-01 18:17
I really need a reproducible example to help, I'm sorry. I don't even get what your problem is at the moment. I'm sorry.
I'll keep this PR around for a while waiting for more details. If they don't arrive, I'll close it as invalid in a few days. 👍

**Comment by MariwanJ** [comment] 2024-03-01 19:56
I explain in simple text. I have classes rather than struct as component. After adding the class objects to the system, directly after that it gets destructed. Seems entt dosent keep them and the shared pointer dies. Look at my video about that. 
https://www.youtube.com/watch?v=aC8pZvzssrs

**Comment by MariwanJ** [comment] 2024-03-02 21:21
you wish to have a simple test. You get it here. Try to add this class to any entt system. and see how the destructor will becalled after creation. 
`
class testit {
 public:
     testit();
     ~testit();
     std::shared_ptr<std::string> test;
     void printIt();
     std::shared_ptr<int> val;
     int w;
 };
 
 test.cpp
testit::testit() {
    val = std::make_shared<int>(10);
    std::make_shared<std::string> ("this is a test");
    std::shared_ptr<int> val;
    w = 1;
};
testit::~testit() {
}
void testit::printIt() {
    std::cout << *test<<std::endl;
    std::cout << *val << std::endl;
    std::cout << w << std::endl;
    }
	
	
   Fr_Item Scene::createtest() {
       auto testItemm = createItem("testit");
       auto gr = testItemm.addItem<testit>();
       return testItemm;
   }
`
Put a stop on the destructor. you will notice tha tas soon as you call createtest(), and return the object, the destructor is already called and the object dies.

**Comment by skypjack** [comment] 2024-03-04 11:13
After asking over and over for a repro so I could help, I now watched a few minutes of an 11 minute video in which someone either insults the author of EnTT or tries to prove that there is a bug in EnTT on the creation of components (which would make the library unusable, it's odd no one noticed).
This is sad because my desire to help clashes with the demand that I invest hours for free to debug a codebase I don't know, when it would be enough to put in the effort like everyone else does to provide an MRE and get the help you need.

I stopped watching the video after seeing yet another reference captured as `auto var = ...` btw which, as we all know, makes a copy of the elements.
My feeling was that you've an issue with your types that aren't correctly defined (ie not movable or with a badly designed move ctor/op), but seeing all the `auto var = ...` captures also makes me doubt about the overall knowledge of the language.

In any case, I'll leave this issue open for a couple more days. If you can provide an MRE you'll have all my help like anyone else so far.

**Closed** 2024-03-04 11:26 UTC
Labels: invalid

**Comment by MariwanJ** [comment] 2024-03-04 14:31
> @MariwanJ, here's a short action plan for you:
> 
>     1. Learn and practice C++ for 5 more years.
> 
>     2. ???
> 
>     3. Return here, re-read the issue and apologize.

Typical reply from people that don't help and start to personal attack. learn how you respect others

**Comment by skypjack** [comment] 2024-03-04 17:13
Stop arguing with each other, thanks. It's useless.
