### ISSUE TITLE
Natvis visualizers out-of-date

### ISSUE THREAD

**Issue by guusw** [skypjack/entt#1026] opened 2023-06-21 06:07 UTC
It seems that the visualizers are currently no longer working. I get various errors when for example trying to inspect a registry:
```
Natvis: C:\Users\...\entt\entity.natvis(7,5): Error: identifier "traits_type" is undefined
    Error while evaluating 'traits_type::type &' in the context of type 'rare.exe!entt::basic_registry<entt::entity,std::allocator<entt::entity>>'.
Natvis: C:\Users\...\entt\container.natvis(14,16): Error: class "entt::internal::dense_map_node<unsigned long long,entt::basic_any<0,8> >" has no member "element"
    Error while evaluating 'packed.first_base::value[$i].element' in the context of type 'rare.exe!entt::dense_map<unsigned long long,entt::basic_any<0,8>,entt::identity,std::equal_to<unsigned long long>,std::allocator<std::pair<const unsigned long long,entt::basic_any<0,8>>>>'.
```

**Comment by skypjack** [comment] 2023-06-21 07:46
Which version of EnTT? I can't reproduce it on `wip` nor on version v3.12.1 at the moment.

**Comment by skypjack** [comment] 2023-06-21 07:48
To be fair, from the error above it looks like you're using old natvis files with a newer version of EnTT.

**Comment by skypjack** [comment] 2023-06-23 08:49
I'm closing this as invalid. Feel free to continue the discussion here if you have any doubts. 👍

**Closed by skypjack** 2023-06-23 08:49 UTC
Labels: invalid
