### ISSUE TITLE
Registry size method with exclude list?

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#553] opened 2020-09-10 11:16 UTC
Hi, is this possible?

```c++
struct PointLight final { ... };
struct Disabled final {};

auto
count_enabled_lights(entt::registry &registry)
{
  return registry.size<PointLight>(entt::exclude<Disabled>);
}
```

Currently I can't find a built-in way to do this, so I'm using this:
```c++
struct PointLight final { ... };
struct Disabled final {};

auto
count_enabled_pointlights(EntitySystem const& registry)
{
  uint64_t accum = 0;
  for (auto const& pl : registry.view<PointLight const>(entt::exclude<Disabled>).proxy())
  {
    ++accum;
  }
  return accum;
}
```

This feels inefficient, I'm assuming the underlying data structures inside the registry can do this operation much more quickly than my shenanigans (at best is linear time w/regards to number of components).

Also, calling size() with an exclude list  **feels good** 😅.

I haven't thought through this beyond my little use case, but if this isn't already implemented what do you think?

**Comment by skypjack** [comment] 2020-09-10 11:49
The registry doesn't really know how many entities are in this set.
You can probably avoid iterations with an observer or a custom listener attached to the signals. In this case you keep your counter up-to-date at any change in the set rather than refreshing it when needed.
Otherwise, you can use a partial owning group and look at its size. In this case, the size of the group is exactly what you want.

**Comment by bjadamson** [comment] 2020-09-10 12:17
> The registry doesn't really know how many entities are in this set.

Ok, fair enough. That makes sense, the view once it's constructed would know about the entities in the set, but not the registry itself.

I found this a bit surprising though, is it intentional that the size() method on the view ignores the exclude list? Here's an example of what I mean: https://godbolt.org/z/KsdE3s

I can file a separate issue if you like for this^.

> You can probably avoid iterations with an observer or a custom listener attached to the signals. In this case you keep your counter up-to-date at any change in the set rather than refreshing it when needed.
Otherwise, you can use a partial owning group and look at its size. In this case, the size of the group is exactly what you want.

Awesome. Thank you for the advice about the observer, I'm taking my time learning features 1 by 1 with entt so I haven't gotten there yet. I'll take a look.

**Comment by skypjack** [comment] 2020-09-10 12:48
> I found this a bit surprising though, is it intentional that the size() method on the view ignores the exclude list?

Yes and no. It's not a bug though, probably just a misleading name.
While `size` returns the exact number of elements for a single component view, the same method [estimates the number of entities iterated by the view](https://github.com/skypjack/entt/blob/master/src/entt/entity/view.hpp#L354) for its multi-component version. This is a direct consequence of the fact that we don't know in advance how many entities there are in the set. 🙂 

> I'm taking my time learning features 1 by 1 with entt so I haven't gotten there yet. I'll take a look.

Sure, feel free to drop your questions if any. You can also join gitter or discord if you want a more direct discussion. 😉

**Comment by bjadamson** [comment] 2020-09-10 15:09
Hmm......... interesting. I'm sorry I missed that in the documentation, I made an assumption to `size()` behavior based on my usage of the STL.

I don't mean to be presumptuous, but do you think renaming the method to `size_hint` is worth considering?

**Comment by skypjack** [comment] 2020-09-11 09:23
Nothing of which to sorry, don't worry.
Actually, your suggestion of renaming it makes perfectly sense. Nobody reads the docs 😄 but everybody reads the function name.
Good point. Thanks for bringing this up. Please, leave the issue open. I'll close it when the renaming is upstream. 👍

**Comment by skypjack** [comment] 2020-09-16 06:55
Available on branch `experimental`. Thanks for the suggestion of renaming it to make it clear the purpose. 👍

**Closed by skypjack** 2020-09-16 06:55 UTC
Labels: enhancement
