### ISSUE TITLE
Support using entt::type_info as key in associative containers

### ISSUE THREAD

**Issue by jonesmz** [skypjack/entt#658] opened 2021-02-14 08:10 UTC
I want to use `entt::type_info` as the key in an associative container (e.g. `std::map`). However, `type_info` has some problems.

```cpp
template<typename Type>
type_info type_id() ENTT_NOEXCEPT;
```

could be constexpr if they didn't include type_seq. My knowledge with constexpr seems to be lacking here, so it's not clear that it's possible to do this at all, so maybe this aspect of the issue can be ignored.

That being said, the type_id() function should be [[nodiscard]]. As a (mostly) pure function, there's no reason to call it without doing something with the result. The default implementation being constexpr (if possible) and [[nodiscard]] wouldn't influence explicit specializations that the end user makes, so probably best not to rely on that inside of EnTT, but if the user of EnTT doesn't implement non-constexpr specializations of type_id<>() then they could take advantage of that. (Again, assuming it's even possible to use constexpr here, which it may not be)

------------------------

`type_seq`, `type_hash` and `type_name` should have implicit conversion operators to allow for short-hand usage.

```cpp
template<typename Type, typename = void>
struct type_seq final {
    [[nodiscard]] static constexpr id_type value() ENTT_NOEXCEPT;
    constexpr operator id_type() const ENTT_NOEXCEPT { return value(); }
};

template<typename Type, typename = void>
struct type_hash final {
    [[nodiscard]] static constexpr id_type value() ENTT_NOEXCEPT;
    constexpr operator id_type() const ENTT_NOEXCEPT { return value(); }
};

template<typename Type, typename = void>
struct type_name final {
    [[nodiscard]] static constexpr std::string_view value() ENTT_NOEXCEPT;
    constexpr operator std::string_view() const ENTT_NOEXCEPT { return value(); }
};
```

Use like:

```cpp
void foo(id_type);
foo(entt::type_seq<MyType>{});
foo(entt::type_seq<MyType>::value()); // same as above.
foo(entt::type_hash<MyType>{});
foo(entt::type_hash<MyType>::value()); // same as above.

void bar(std::string_view);
foo(entt::type_name<MyType>{});
foo(entt::type_name<MyType>::value()); // same as above.
```

`type_seq`, `type_hash`, `type_name`, and `type_info` should define comparison operators. If you want to be lazy, just `operator<=>` from C++20 would probably work fine. It's not clear to me that defining comparisons against either of id_type of std::string_view would make sense on their own, but EnTT may have internal rules that I'm not aware of that require uniqueness for both of these independently and also together, and as such maybe it does make sense.

------------------------

Is there a reason for id_type being used for both `type_hash` and `type_seq` ? I would have expected these to be different types, since they are inherently not comparable against each other.

------------------------

Also, I'm kind of confused at:

1. Overloads of internal::type_hash and internal::type_name with char and int, but only (apparently?) the int overload used? What's the goal of having two overloads, and would it be easier for the reader to understand if these were std::true_type / std::false_type, or specific empty tag-structs that clearly denote what the two overloads are for?
2. Inconsistent use of static and constexpr for intermediate variables for all of these functions.

For 2, some examples:

All of these variables can be static constexpr, including pretty_function. Without marking them as static constexpr, there's a good chance the compiler will do work at runtime if these functions are called at runtime on lower optimization levels. (Observed in the wild with MSVC, for example, on my job's codebase)
```cpp
template<typename Type>
[[nodiscard]] constexpr auto stripped_type_name() ENTT_NOEXCEPT {
#if defined ENTT_PRETTY_FUNCTION
    std::string_view pretty_function{ENTT_PRETTY_FUNCTION};
    auto first = pretty_function.find_first_not_of(' ', pretty_function.find_first_of(ENTT_PRETTY_FUNCTION_PREFIX)+1);
    auto value = pretty_function.substr(first, pretty_function.find_last_of(ENTT_PRETTY_FUNCTION_SUFFIX) - first);
    return value;
#else
    return std::string_view{};
#endif
}
```

The variables in this function can be static as well.
```cpp
template<typename Type, auto = stripped_type_name<Type>().find_first_of('.')>
[[nodiscard]] static constexpr id_type type_hash(int) ENTT_NOEXCEPT {
    constexpr auto stripped = stripped_type_name<Type>();
    constexpr auto value = hashed_string::value(stripped.data(), stripped.size());
    return value;
}
```

------------------------

Reading https://github.com/skypjack/entt/wiki/Crash-Course:-core-functionalities#almost-unique-identifiers

I have a suggestion for how to help overcome the conflicting type names + hashes.

Consider providing a macro that can be defined with a user specified prefix or suffix to be included in the typename that is hashed.

You could provide 4 such macros.
- Prefix / suffix for type_name itself.
- prefix / suffix for hash, which also would include the prefix/suffix for type_name, if provided.
These could, optionally, provide the consumer of entt a mechanism to avoid multiple dlls having conflicting hashs, though they would need to be used with care, certainly.

------------------------

A final consideration.

It would be an ABI break, but what about using an inline template variable for `type_seq`, `type_hash`, `type_name`, and eschew the ::value() functions entirely?

E.g.
```cpp
#if defined ENTT_PRETTY_FUNCTION
    template<typename TYPE_T>
    inline id_type type_hash = internal::type_hash<Type>(0);
#else
    template<typename TYPE_T>
    inline id_type type_hash = type_seq<Type>::value();
#endif

template<typename TYPE_T>
inline std::string_view type_name = internal::type_name<Type>(0);
```

**Comment by skypjack** [comment] 2021-02-14 10:02
This is... huge. 😄 Let's try to answer all of your doubts.

> I want to use `entt::type_info` as the key in an associative container (e.g. `std::map`).

It's not really meant for that, as it isn't `std::type_info`. You should use the sequential identifier or the hashed name as a key. They are integral types and offer out of the box all you need for that already.


> However, `type_info` has some problems.
> 
> ```c++
> template<typename Type>
> type_info type_id() ENTT_NOEXCEPT;
> ```
> 
> could be constexpr if they didn't include type_seq.

Yeah, but it includes `type_seq` for a reason. So... 🙂 

> That being said, the type_id() function should be [[nodiscard]].

Good catch. 👍 You're right.

> The default implementation being constexpr (if possible)

To make `type_id` constexpr, `type_info` should have at least a constexpr constructor. It doesn't make sense at the moment, since `type_seq` isn't constexpr **but** in theory you could redefine it and make it constexpr.
To be honest, I don't really see a reason for that. If you want a constexpr key for your maps for some reason, you should rather use `type_hash<T>::value()` directly probably.

> `type_seq`, `type_hash` and `type_name` should have implicit conversion operators to allow for short-hand usage.

`value` is static, the conversion operator couldn't be so. Not sure I see the advantages here, but still, it seems feasible.

> `type_seq`, `type_hash`, `type_name`, and `type_info` should define comparison operators. If you want to be lazy, just `operator<=>` from C++20 would probably work fine.

I can't _be lazy_ here, because EnTT is a C++17 library at the moment.
In any case, they shouldn't define comparison operators at all. Becuase `value` is static, they don't need to. The returned value is also already comparable (it's an integral type after all).
I don't see why we should add more and more code to maintain for no real benefits.

> Is there a reason for id_type being used for both `type_hash` and `type_seq` ? I would have expected these to be different types, since they are inherently not comparable against each other.

`type_hash` **is** `type_seq` when for example `ENTT_STANDARD_CPP` is defined. So, they may be the same, yeah, and are definietely comparable.
It's like saying that the returned values of two different hashing functions aren't inherently comparable. They are in fact, since probably the two functions both return integral values. 🤷‍♂️ 

> 1. Overloads of internal::type_hash and internal::type_name with char and int, but only (apparently?) the int overload used? What's the goal of having two overloads, and would it be easier for the reader to understand if these were std::true_type / std::false_type, or specific empty tag-structs that clearly denote what the two overloads are for?

It's a sfinaed call. See `auto = stripped_type_name<Type>().find_first_of('.')`.
All this is required to take in account some nasty issues with older compilers. I won't go in details because it would require the whole Sunday 😄 but the commit messages as well as gitter/discord contain tons of details on these points.

> 2. Inconsistent use of static and constexpr for intermediate variables for all of these functions.

Same as above unfortunately. It's not inconsistency. These variables are from macroed sections that just work for a compiler or the other.

> For 2, some examples:
> 
> All of these variables can be static constexpr, including pretty_function.

Well, no, this is a good example already. `PRETTY_FUNCTION` is a non-standard extension and therefore you have no guarantees. In particular, it wasn't constexpr in older version of GCC (< 8 if I remember it correctly).

> Without marking them as static constexpr, there's a good chance the compiler will do work at runtime if these functions are called at runtime on lower optimization levels. (Observed in the wild with MSVC, for example, on my job's codebase)

In theory, that part is designed to avoid this. Either with constexpr values or using static variables where the constexpr flavor isn't available (see above). So, it shouldn't do work at runtime. Of course, there may be an error but I need a reproducible example in this case.
 
> I have a suggestion for how to help overcome the conflicting type names + hashes.

All `type_*` utilities are sfinae-friendly. You can already do this if needed. 👍 

> It would be an ABI break, but what about using an inline template variable for `type_seq`, `type_hash`, `type_name`, and eschew the ::value() functions entirely?

It was like that initially. However, it breaks when `__declspec(dll*)` is defined (see `ENTT_API`). So, I had to change it because of a compiler issue. 🤷‍♂️

**Comment by jonesmz** [comment] 2021-02-14 21:07
> This is... huge. smile Let's try to answer all of your doubts.
> 
> > I want to use `entt::type_info` as the key in an associative container (e.g. `std::map`).
> 
> It's not really meant for that, as it isn't `std::type_info`. You should use the sequential identifier or the hashed name as a key. They are integral types and offer out of the box all you need for that already.

Respectively, I disagree. You make it clear in the 3.6.0 release notes that hash collisions can occur, so the combination of type_seq, type_hash, and type_name are more unique than any of the three individually. Obviously there's the additional cost of an extra integer comparison, and a pointer+size_t comparison, but that's cheap in the grand scheme of things. Much better than full string comparisons, which my codebase is currently doing anyway.

 Adding
```
#ifdef C++20
 operator<=>(type_info) = default;
#endif
```
*should* work out of the box for users of EnTT that use C++20 compilers, without any additional work from you.

> 
> > However, `type_info` has some problems.
> > ............
> > could be constexpr if they didn't include type_seq.
> 
> Yeah, but it includes `type_seq` for a reason. So... slightly_smiling_face

The function itself can still be constexpr, because your users might make a specialization for type_seq that is constexpr.

constexpr template functions will degrade to non-constexpr when the implementation can't be. But non-constexpr templates can never be used as constexpr.


> > The default implementation being constexpr (if possible)
> 
> To make `type_id` constexpr, `type_info` should have at least a constexpr constructor. It doesn't make sense at the moment, since `type_seq` isn't constexpr **but** in theory you could redefine it and make it constexpr.
> To be honest, I don't really see a reason for that. If you want a constexpr key for your maps for some reason, you should rather use `type_hash<T>::value()` directly probably.

the `type_info` struct itself can be constexpr so long as entt::id_type and std::string_view can be constexpr constructed. 
I would consider it reasonable to use a macro to allow users of entt to turn that off if they want to use an entt::id_type that can't be constexpr constructed. 

I thought that C++20 added some kind of constexpr(bool) notation, but I can't find any documentation on that, so maybe it's something being considered for c++23.


> > `type_seq`, `type_hash` and `type_name` should have implicit conversion operators to allow for short-hand usage.
> 
> `value` is static, the conversion operator couldn't be so. Not sure I see the advantages here, but still, it seems feasible.

My objective with this request is merely to reduce typing.



> > `type_seq`, `type_hash`, `type_name`, and `type_info` should define comparison operators. If you want to be lazy, just `operator<=>` from C++20 would probably work fine.
> 
> I can't _be lazy_ here, because EnTT is a C++17 library at the moment.
> In any case, they shouldn't define comparison operators at all. Becuase `value` is static, they don't need to. The returned value is also already comparable (it's an integral type after all).
> I don't see why we should add more and more code to maintain for no real benefits.
> 

My meaning was to only offer this for C++20 environments. E.g. `#ifdef C++20 /**/ #endif` kind of thing.
I can see your intention for `type_seq`, `type_hash`, and `type_name`, though I'm not completely convinced there's no utility to having the comparison operators provided.
We already talked about `type_info` above, so i'll not address that twice.

> > Is there a reason for id_type being used for both `type_hash` and `type_seq` ? I would have expected these to be different types, since they are inherently not comparable against each other.
> 
> `type_hash` **is** `type_seq` when for example `ENTT_STANDARD_CPP` is defined. So, they may be the same, yeah, and are definietely comparable.
> It's like saying that the returned values of two different hashing functions aren't inherently comparable. They are in fact, since probably the two functions both return integral values. man_shrugging

They are only comparable when `ENTT_STANDARD_CPP` is defined, or when a specialization is provided by the end-user that makes them the same.

It's true that two different hashing algorithm might return an integral type, and thus the outputs can be compared in the meaning of integer comparisons, but it's not a meaningful comparison. If your MD5 and SHA256 algorithm are returning the same integral value, that doesn't speak much to whether the items that they hashed to get that integral value are comparable in any generic sense.

It happens to be the case that you've design the `type_hash` to use `type_seq` as a fallback, but I don't think that it's reasonable to claim that they return concepts / types that are comparable in any meaningful way without relying on insider knowledge.

My recommendation is that you make these functions return different types, and define some `id_hash_from_seq(id_seq)` function that, by default, simply returns the provided numeric value. This way, if the end-user provides different types for hashing versus sequencing, they have a safety valve to adapt their custom types to the internals of the entt framework (or perhaps this would be adapting the entt framework to their custom type).

The default behaviour can, of course, remain that `id_hash` and `id_seq` are just integers, if the user of entt doesn't provide their own definitions.

Similarly, I recommend providing an end-user facing way to tweak the type_name item. For example, I have a custom string implementation that is a better fit for the workload that I'm doing, which is API comparable (nearly identical, really) to `std::string_view`, and I can see using that for `type_info` instead of `std::string_view`

> > 1. Overloads of internal::type_hash and internal::type_name with char and int, but only (apparently?) the int overload used? What's the goal of having two overloads, and would it be easier for the reader to understand if these were std::true_type / std::false_type, or specific empty tag-structs that clearly denote what the two overloads are for?
> 
> It's a sfinaed call. See `auto = stripped_type_name<Type>().find_first_of('.')`.
> All this is required to take in account some nasty issues with older compilers. I won't go in details because it would require the whole Sunday smile but the commit messages as well as gitter/discord contain tons of details on these points.

Ah. I see.

Wouldn't it be more appropriate to use your choice<N> type from type_traits.hpp ?

I fully understand the issues with supporting older compilers, I've been dealing with code exactly like what you have here for years, which is why I'm making the recommendations I am.

> > 1. Inconsistent use of static and constexpr for intermediate variables for all of these functions.
> Well, no, this is a good example already. `PRETTY_FUNCTION` is a non-standard extension and therefore you have no guarantees. In particular, it wasn't constexpr in older version of GCC (< 8 if I remember it correctly).

Then how can the whole function be constexpr, if the individual variables cannot?

To be perfectly honest, I don't see how it's worth it to allow newer compilers to suffer because of older compilers. The way I'd approach this kind of thing is to put an `#ifdef OLD_BROKEN_COMPILER` around the entire function, and let the non-broken compiler version of the function use the correct keywords.

> > Without marking them as static constexpr, there's a good chance the compiler will do work at runtime if these functions are called at runtime on lower optimization levels. (Observed in the wild with MSVC, for example, on my job's codebase)
> 
> In theory, that part is designed to avoid this. Either with constexpr values or using static variables where the constexpr flavor isn't available (see above). So, it shouldn't do work at runtime. Of course, there may be an error but I need a reproducible example in this case.

In the general sense, static variables without the constexpr keyword, have the cost of an atomic initializer guard flag, and ugly code gen. Sometimes on high (e.g. -O3) compilation settings those restrictions evaporate, and MSVC is especially hard to make it not emit the atomic initializer code. But "static constexpr" never has that, as far as I've ever been able to test.

> > I have a suggestion for how to help overcome the conflicting type names + hashes.
> 
> All `type_*` utilities are sfinae-friendly. You can already do this if needed. +1

My basic point was that if it's enough of a possibility that you have to write several paragraphs about the subject in the release notes, it's a situation that will happen enough that you would want to provide a built in mechanism to overcome the problem.
By default, the solution should work for 90% of the cases. Then, you provide a macro that can cover 9% of the additional cases, leaving the library as solving 99% of cases. Then, for the remaining 1%, they can use the sfinae method for all of their types, to work around whatever broken toolchain that they are using.

If it wasn't a common enough problem for you to write about how to work around it, then something like a macro / constexpr defined prefix / suffix system wouldn't be a suggestion worth making.

> > It would be an ABI break, but what about using an inline template variable for `type_seq`, `type_hash`, `type_name`, and eschew the ::value() functions entirely?
> 
> It was like that initially. However, it breaks when `__declspec(dll*)` is defined (see `ENTT_API`). So, I had to change it because of a compiler issue. man_shrugging

Ah, I understand.

**Comment by skypjack** [comment] 2021-02-14 23:30
> hash collisions can occur, so the combination of type_seq, type_hash, and type_name are more unique than any of the three individually

I would discourage this practice. In case of collisions, you can either avoid them working _externally_ (that is, you can use a different name for a colliding element) or you can specialize on a per-type basis the type hash struct. In both cases, you've a much faster alternative to comparing sequence, hash and name all the times, especially if you consider that the three aren't required nor guaranteed to be compile-time expressions.
 
> Adding
> 
> ```
> #ifdef C++20
>  operator<=>(type_info const&) = default;
> #endif
> ```
> 
> _should_ work out of the box for users of EnTT that use C++20 compilers, without any additional work from you.

I'd rather avoid this too. EnTT is a C++17 library at the moment, aimed at working in environment where C++17 is the commonly supported revision of the language. I don't want an `#ifdef C++20` token to leak all over the codebase.
Sooner or later, I'll freeze the C++17 version and start working on a C++20 one, as it happened when I moved from C++14 to C++17. This is still a sort of free time project, don't be fooled by the fact that many use it. I don't want and don't have the bandwidth to support multiple revisions of the standard at once, nor I think that already supporting C++20 would be a good idea.

> The function itself can still be constexpr, because your users might make a specialization for `type_seq` that is constexpr.
> [...]
> the `type_info` struct itself can be constexpr so long as `entt::id_type` and `std::string_view` can be constexpr constructed.

Yeah, makes sense.

> I would consider it reasonable to use a macro to allow users of entt to turn that off if they want to use an entt::id_type that can't be constexpr constructed.

You don't really need a macro here. Just don't create your objects with compile-time expressions. A constexpr constructor doesn't mean that all created objects are constexpr just because.
 
> > `type_seq`, `type_hash` and `type_name` should have implicit conversion operators to allow for short-hand usage.
>
> My objective with this request is merely to reduce typing. The extra `::value()` needing to be repeated every time I want to query the `type_name` is quite annoying.

🙂 

> > `type_seq`, `type_hash`, `type_name`, and `type_info` should define comparison operators. If you want to be lazy, just `operator<=>` from C++20 would probably work fine.
> > 
> My meaning was to only offer this for C++20 environments. E.g. `#ifdef C++20 /**/ #endif` kind of thing.

This isn't really a solution. Even if I wanted to leak that `ifdef`all over the codebase, I'd still need to provide an alternative for non-C++20 users.
EnTT is mainly used in the game industry and C++20 isn't a thing there yet (actually, it's not a thing in general yet, if we consider compiler support and portability).

> I can see your intention for `type_seq`, `type_hash`, and `type_name`, though I'm not completely convinced there's no utility to having the comparison operators provided. Especially if you add the comparison against `entt::id_type`, which cuts down on boilerplate that your end users would have to use. E.g.
> 
> ```c++
> entt::id_type bob;
> if(bob == type_hash<MyType>{}) { ... }
> ```
> 
> Is a simplified example of why this would be useful. (though, the implicit conversion would cover _THIS_ situation).

As a side note, to make this works, a conversion operator would be enough. 

> Here's a more complex one.
> 
> ```c++
> template<typename ONE_T, typename TWO_T>
> static_assert(MyLib::do_complex_thing_returning_entt_type_name<ONE_T> == MyLib::do_DIFFERENT_Complex_thing_returning_entt_type_name<TWO_T>);
> ```
> 
> The provision of comparison operators between `type_hash` and other `type_hash` instantiations would cut down on end-user boilerplate. The goal isn't to provide functionality they can't accomplish on their own, but it does help with avoiding annoying code patterns.

I don't get the example. Something like `type_hash` isn't meant to be instantiated and only offers static functions in its API.
If you really want to avoid this _annoying code pattern_:
```
do_complex_thing_returning_entt_type_name<ONE_T>::value() == do_complex_thing_returning_entt_type_name<TWO_T>::value()
```
You can make your function return the _right_ type, that is, the hashed value. It already supports all comparison functions and seems like the right thing to return here.

> > I don't see why we should add more and more code to maintain for no real benefits.
> 
> One tiny inline function per type (for 3 types) is not very much of a maintenance burden. I would understand your reluctance if my proposal required hundreds of lines of code, of course.

Unfortunately, it isn't a tiny inline function. To make it work with C++17, it's 5 operators for 3 classes. Just to offer what a call to `::value`already offers out of the box. So, yeah, I'm a bit reluctant. 🙂 

> It happens to be the case that you've design the `type_hash` to use `type_seq` as a fallback, but I don't think that it's reasonable to claim that they return concepts / types that are comparable in any meaningful way without relying on insider knowledge of how EnTT is built, and I would further argue that it's a serious end-user bug if they are comparing `type_hash` and `type_seq`'s returned `id_type`s against each other. Enough of one that it should be a compilation error, IMHO.
> 
> In one of my codebases, I use something like `enum class MyId : int16_t {}` and `enum class MyOtherId : int16_t {}` to make "opaque id types" incomparable to each other (without static casts, of course)

I see what you mean. Though, it's like pretending that `std::vector<T>::capacity` and `std::vector<T>::size` didn't return the same type because users could compare them by mystake. I mean, sure, users can do it, but I don't want to make it more cumbersome for all other users that decided to not shoot in their feet (where _all other users_ means me too, because these two functions are widely used within the rest of the library).

> My recommendation is that you make these functions return different types, and define some `id_hash_from_seq(id_seq)` function that, by default, simply returns the provided numeric value. This way, if the end-user provides different types for hashing versus sequencing, they have a safety valve to adapt their custom types to the internals of the entt framework (or perhaps this would be adapting the entt framework to their custom type).

It's not that easy unfortunately. The per-type sfinae-friendly nature requires that the types are fixed and known in advance.
So, users cannot decide all of a sudden that their hashing functions return a `struct my_type` without breaking the internals of the library. It may be possible with a bunch of macros used literally everywhere, but imho there is no real advantage in this kind of flexibility.

> Similarly, I recommend providing an end-user facing way to tweak the type_name item. For example, I have a custom string implementation that is a better fit for the workload that I'm doing, which is API comparable (nearly identical, really) to `std::string_view`, and I can see using that for `type_info` instead of `std::string_view`

Same as above. We can change the _required type_, but it's a little annoying to make it fully customizable and it probably requires its own macro. As for the name, it's limited in scope and may be viable. Though, I'd probably turn it in a `char *`and size pair, something that does fit the vast majority of reasonable cases.

> I could also see a use-case where a user of entt would want their `type_name` to return an index / iterator to a global container that has the std::string_view, with an implicit conversion operator, because their use of type_name for some reason takes up too much storage, and they want to slim things down, but pay more for rendering the `type_name` into an actual string. Couldn't say beyond that I can see how someone would go about doing that.

True. I can see how users could want to do lot of things that aren't allowed by this library. Though, we can't design for maximum flexibility and offer all possible customization points to match all cases that could ever knock at our door. I don't want 1M macros nor to have to maintain ugly code just because someone, who knows when, could want to do who knows what.
EnTT offers _some tools_. It has customization points for a lot of things here and there, while it took some decisions and set some constraints somewhere else for many reasons.
The `type_info` class is an example of this. It's designed as a sfinae-friendly tool that users can customize to some degree. If it doesn't fit the requirements, well, nothing prevents users from rolling a _better tool_ for the purpose.

> Wouldn't it be more appropriate to use your `choice<N>` type from type_traits.hpp ?

Well, yes and no. For two overloads, you don't need it and it's one less include, other then less template specializations.

> Then how can the whole function be constexpr, if the individual variables cannot? Your explanation reminds me of the similar compiler _bugs_ that I encountered with GCC's handling of the PRETTY_FUNCTION variable. The PRETTY_FUNCTION variable may not be fully specified, and thus compiler specific, but GCC's handling of it has been simply broken for a long time.

The function within `type_name` is constexpr, but its constexprness depends on the invoked function. `internal::type_name` is sfinaed instead, constexpr when the pretty function is constexpr, not constexpr otherwise. So, overall, the type name value is constexpr if the value at the source is constexpr, that is, if the compiler offers a constexpr pretty function.
Not sure I get your objection. Are you experiencing problems with this function or it's just a guess that it may not work?

> To be perfectly honest, I don't see how it's worth it to allow newer compilers to suffer because of older compilers. The way I'd approach this kind of thing is to put an `#ifdef OLD_BROKEN_COMPILER` around the entire function, and let the non-broken compiler version of the function use the correct keywords.

That's what's happening here. The _if-old-compiler_ part is buried in another file, because I don't want to leak this kind of things all over the codebase. Though, yeah, if you put all pieces together, this is exactly what's happening. My feeling is that we are only discussing of a stylistic choice, unless I'm missing the problem you're trying to point out.
There is no compiler that suffers because of another compiler at the moment. At least, none of which I'm aware, but I may be wrong of course. If there is an actual problem, a reproducible example to explain it would really help.

> In the general sense, static variables without the constexpr keyword, have the cost of an atomic initializer guard flag, and ugly code gen. Sometimes on high (e.g. -O3) compilation settings those restrictions evaporate, and MSVC is especially hard to make it not emit the atomic initializer code. But "static constexpr" never has that, as far as I've ever been able to test.

Though, here the problem is the opposite one. You pointed out a constexpr variable without a static keyword, not a static variable without a constexpr keyword. The former should emit the same code in all cases. Am I wrong?

> My basic point was that if it's enough of a possibility that you have to write several paragraphs about the subject in the release notes, it's a situation that will happen enough that you would want to provide a built in mechanism to overcome the problem.
> By default, the solution should work for 90% of the cases. Then, you provide a macro that can cover 9% of the additional cases, leaving the library as solving 99% of cases. Then, for the remaining 1%, they can use the sfinae method for all of their types, to work around whatever broken toolchain that they are using.

I wrote a paragraph in the documentation because the documentation contains a paragraph for... literally... everything! 😄 
So far, I've never encountered nor I've ever been reported of a conflict to be honest. EnTT uses a possibly constexpr fnv-1a hashing algorithm in a space of 32b by default, 64b if you like. You can customize the hashing function on a per-traits and per-type basis if needed and the library is usually used in contexts where users have full control on the names to hash.
I'm pretty confident that the solution works for 99% of cases out of the box and the customization points can solve the remaining 1%. Two additional macros seem to me cumbersome, especially if you consider that users can specialize the `type_name` class for all types at once already and add the prefix/postifx extension on their own if needed.

> If it wasn't a common enough problem for you to write about how to work around it, then something like a macro / constexpr defined prefix / suffix system wouldn't be a suggestion worth making.

It's definitely not a common enough problem. 🙂 
I wrote about the customization points as I wrote about anything else in the library.

**Comment by skypjack** [comment] 2021-02-19 09:18
I'm closing this issue because I ported upstream the relevant changes and keep thinking that the suggested solution of using the hashed value rather than a `type_info` object is the right thing to do here.
I don't see any other change to perform, but I must admit that the discussion was very interesting and I learnt a few things of which I wasn't aware. So, thank you for your time.
Feel free to continue the discussion and to suggest other changes that I may have missed if required. Thanks.

**Closed by skypjack** 2021-02-19 09:18 UTC
Labels: triage

**Comment by jonesmz** [comment] 2021-02-21 19:15
We've gone deep enough into the other subjects that I brought up that I don't think those need to be addressed any further.

But I did have a small number of followups.

> Unfortunately, it isn't a tiny inline function. To make it work with C++17, it's 5 operators for 3 classes. Just to offer what a call to `::value`already offers out of the box. So, yeah, I'm a bit reluctant. 🙂

I don't understand how this code is 5 operators for 3 classes? It's three 1-liners.

```cpp
template<typename Type, typename = void>
struct type_seq final {
    [[nodiscard]] static constexpr id_type value() ENTT_NOEXCEPT;
    constexpr operator id_type() const ENTT_NOEXCEPT { return value(); }
};

template<typename Type, typename = void>
struct type_hash final {
    [[nodiscard]] static constexpr id_type value() ENTT_NOEXCEPT;
    constexpr operator id_type() const ENTT_NOEXCEPT { return value(); }
};

template<typename Type, typename = void>
struct type_name final {
    [[nodiscard]] static constexpr std::string_view value() ENTT_NOEXCEPT;
    constexpr operator std::string_view() const ENTT_NOEXCEPT { return value(); }
};
```

Were you responding to both my request for operator<=> and also implicit conversion operators at the same time?

> I see what you mean. Though, it's like pretending that `std::vector<T>::capacity` and `std::vector<T>::size` didn't return the same type because users could compare them by mystake. I mean, sure, users can do it, but I don't want to make it more cumbersome for all other users that decided to not shoot in their feet (where all other users means me too, because these two functions are widely used within the rest of the library).

Forgive me, but I just don't see how your counter example applies.

You *do* want to check if the capacity of a vector is larger than or equal to it's current size (or it's current size + some number) in lots of situations, because that's how you check to see if you need to allocate more space. `std::vector<T>::resize` and `std::vector<T>::reserve`. The API of `std::vector<T>::capacity` and `std::vector<T>::size` explicitly says that they return values that represent the same concept and are intended to be comparable. E.g. "number items". For `size`, it's "number items in the container" and `capacity` it's "number of items that the container can hold before reallocating".

I cannot think of a situation where comparing a `entt::type_seq` and a `entt::type_hash` is ever a valid thing to do. Even for code where `ENTT_STANDARD_CPP` is defined, those codebases can, and should, use the appropriate comparison.

Could you give me an example where comparing a `seq` to a `hash` is the best approach over comparing a `seq` to a `seq` and a `hash` to a `hash` ?

**Comment by skypjack** [comment] 2021-02-22 08:32
> Were you responding to both my request for operator<=> and also implicit conversion operators at the same time?

I guess so, yeah. 😄 Let me create a dedicate issue for that. 👍 

> You do want to check if the capacity of a vector is larger than or equal to it's current size

Ahah, fair enough. Not the best example ever. 🙂 
Let's say that it's as if someone asked to differentiate the return types of `offsetof` and `vector<T>::size` or any other method that returns an `std::size_t`, or even the `size_type` of a vector and that of a map and so on. The fact is that even the standard library has a sort of opaque and platform dependent catch-all type used all over, namely `std::size_t`. It's how things work and nobody ever considered the possibility of better encapsulating these _types_ by making them strong integral types that you can't mix.
As for EnTT, there is no situation in which comparing the value returned by `type_seq` and that returned by `type_hash` makes sense as far as I can tell, but this doesn't mean that they should have different types. I don't see any case in which `offsetof(clazz, member) == vec.size()` makes sense too, but [I can do it](https://godbolt.org/z/rqq8KG) if I like and I'm fine with it.
The main problem is that giving them actual different types would complicate some things, break existing code and help only in the case in which users decide to compare apples with pears, that is imho an error user side that shouldn't be _fixed_ by the library itself, as you correctly pointed out:

> those codebases can, and should, use the appropriate comparison
