### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by loudedtwist** [skypjack/entt#83] opened 2018-05-27 16:00 UTC
I had an old version of the entt and it worked just fine, but after update today, I'am getting this error trying to build the simple example from the README file:
`In file included from c:\users\warik\code\ecsgameloop\third_party\entt\entt.hpp:7:0,
                 from C:\Users\warik\Code\ecsGameLoop\third_party\main.cpp:1:
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp: In function 'void entt::dependency(entt::Sink<void(entt::Registry<Entity>&, Entity)>)':
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp:54:19: error: parse error in template argument list
     sink.template connect<dependency<Entity, Dependency...>>();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp:54:19: error: expected identifier
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp: In function 'void entt::dependency(entt::break_t, entt::Sink<void(entt::Registry<Entity>&, Entity)>)':
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp:77:19: error: parse error in template argument list
     sink.template disconnect<dependency<Entity, Dependency...>>();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\users\warik\code\ecsgameloop\third_party\entt\entity/helper.hpp:77:19: error: expected identifier
mingw32-make.exe[3]: *** [CMakeFiles/TestMainEntt.dir/main.cpp.obj] Error 1
mingw32-make.exe[2]: *** [CMakeFiles/TestMainEntt.dir/all] Error 2
`
My setup: Windows 10, mingw32 5.0, g++ 6.3.0

**Comment by skypjack** [comment] 2018-05-27 16:39
Did you obtain it by compiling the tests? Otherwise, can you provide a minimal example so as to be able to reproduce the error?

**Comment by loudedtwist** [comment] 2018-05-27 16:55
Hey, that was my code example I was trying to compile:
`#include <entt/entt.hpp>
#include <cstdint>

struct Position {    float x; float y; };

struct Velocity {    float dx; float dy; };

void update(entt::DefaultRegistry &registry) {
    auto view = registry.view<Position, Velocity>(); 
    for(auto entity: view) { 
        auto &velocity = view.get<Velocity>(entity); 
        velocity.dx = 0.;
        velocity.dy = 0.; 
    }
}

void update(std::uint64_t dt, entt::DefaultRegistry &registry) {
    registry.view<Position, Velocity>().each([dt](auto entity, auto &position, auto &velocity) { 
        position.x += velocity.dx * dt;
        position.y += velocity.dy * dt; 
    });
}

int main() {
    entt::DefaultRegistry registry;
    std::uint64_t dt = 16; 
    for(auto i = 0; i < 10; ++i) {
        auto entity = registry.create();
        registry.assign<Position>(entity, i * 1.f, i * 1.f);
        if(i % 2 == 0) { registry.assign<Velocity>(entity, i * .1f, i * .1f); }
    } 
    update(dt, registry);
    update(registry); 
}`

**Comment by loudedtwist** [comment] 2018-05-27 17:10
hey again, could it be some namespace collisions ? after I changed those functions it compiles now: 

```
template<typename... Dependency, typename Entity>
void dependency(entt::Sink<void(entt::Registry<Entity> &, const Entity)> sink) {
sink.template connect<entt::dependency<Entity, Dependency...>>();
} 

template<typename... Dependency, typename Entity>
void dependency(entt::break_t, entt::Sink<void(entt::Registry<Entity> &, const Entity)> sink) {
sink.template disconnect<entt::dependency<Entity, Dependency...>>();
}
```

I added entt:: namespace in front of break_t, Sink, Registry

**Comment by skypjack** [comment] 2018-05-27 19:26
It seems that GCC 6.3 is wrong anyway. I'm not sure I want to update the code that way, it's unnecessary and the policy of `EnTT` hadn't been to support old buggy compilers so far.

**Comment by skypjack** [comment] 2018-05-27 19:40
I'm not able to reproduce the error in any case. I'm testing it with g++ 5 and g++6, using the code you posted above.  
Unless you manage to suggest me a way to reproduce the error, I must mark it as invalid and therefore close the issue. I'm sorry.

**Comment by loudedtwist** [comment] 2018-05-27 20:16
I will try to reproduce it at work tomorrow. Thank you for your time anyway :)

**Comment by skypjack** [comment] 2018-05-27 20:30
You're welcome. The problem is that your example compiles fine with g++ 5, g++ 6 and clang (I don't remember which version I used to test it). Moreover, everything works just fine on MSVC.  
So far, it looks like it's either a problem in your code (but I don't think so actually, for it's really simple) or a problem of the g++ version shipped along with mingw, that isn't namely a _supported platform_. I'm sorry.  
Moreover, the _patch_ you suggested doesn't match in terms with the error you posted and it smells a lot honestly.  
If you can provide more details on how to reproduce it or, even better, you can point me to an online tool where you are able to reproduce the error, it would be great.

**Comment by skypjack** [comment] 2018-05-28 11:10
Any news on this? I tried once more to reproduce the error on the supported platforms, but I failed.  
Unless you can come up with all the details to reproduce it, I'm tempted to close the issue.
In this case, feel free to reopen it whenever you have enough details. Not a problem.

**Comment by loudedtwist** [comment] 2018-05-28 11:35
Hey, I tested it today on my work's computer (Ubuntu 16.04, g++ 5.4.0) and it works 0_o . So it might be a Windows/minGW (I use it because CLion uses it, but I can try it with Cygwin instead) issue...

**Comment by skypjack** [comment] 2018-05-28 11:40
Good to know. I mean, I'm sorry for you, but I've nothing to do on `EnTT` at least. :-)  
I'm closing the issue in the meantime. Feel free to reopen it if you find it's due to a bug in `EnTT` instead.  
Do not forget also to star the project, it will help to attract more users and therefore more contribution!! ;-)

See you soon and thank you for using `EnTT`.

**Closed by skypjack** 2018-05-28 11:40 UTC
Labels: invalid
