### ISSUE TITLE
Registry destroy/remove causing bugs in my code

### ISSUE THREAD

**Issue by cpusam** [skypjack/entt#968] opened 2023-01-02 21:20 UTC
I'm having problems with the registry.destroy/remove. Basically, all times I call registry.destroy(entity) and follow create some entity with differents components some entities disappear. Searching, I found that entt recycle entity, so, can this "feature" reuse some components from a deleted entity?

I'm with almost 3 days with the same bug and it happens only on call of any destroy/remove **inside a callback function**. The callback is called in some time inside a for loop. So, how can I disable entity recycle? Is this possible?

Some solution to that?

**Comment by Green-Sky** [comment] 2023-01-02 22:04
> how can I disable entity recycle

you could create your own definition for an `entity` and set the version bitmask to ... nothing.


BUT this looks like you are doing funky stuff within the callback.
excerpt from the wiki:
> Assigning and removing components from within the body of a listener that observes the destruction of instances of a given type should be avoided. It can lead to undefined behavior in some cases. This type of listeners is intended to provide users with an easy way to perform cleanup and nothing more.

https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#observe-changes

**Comment by skypjack** [comment] 2023-01-04 10:52
@cpusam I can safely assume and assure you that `destroy` and `remove` work as expected.
Without a repro, it's hard to say what's wrong in the calling code. I'm willing to help but the issue is invalid as it stands.

**Comment by cpusam** [comment] 2023-01-11 09:59
Solved. After almots 7 days, I solved with this:
1-removed all entt references and code
2-create a simples ECS
Now, the game runs perfectly! :)

**Comment by skypjack** [comment] 2023-01-11 10:34
Cool. I'm really glad you fixed it. I also like to reinvent the wheel rather than understanding my errors after all.
We can finally close the issue and hide to the rest of the world that both `destroy` and `remove` are broken. Thanks! 🥳

**Closed by skypjack** 2023-01-11 10:34 UTC
Labels: invalid

**Comment by cpusam** [comment] 2023-01-11 18:43
@skypjack
Y0d4: may the bugs be with you!
