### ISSUE TITLE
Range destroy doesn't work properly with views/groups.

### ISSUE THREAD

**Issue by kwarkGorny** [skypjack/entt#261] opened 2019-06-12 20:53 UTC
Hello everyone, I am getting strange out of the bound assert "vector subscript out of range" on VS2019(also VS2017) on Debug for x64 when I try to remove all obsoletes like shown in wiki (it happens even if there is only one obselete to destroy): 
```cpp
struct Obsolete{}; // definition of Obselete struct
...
// somewhere in the end of update
const auto obseletes = registry.view<Obsolete>(); 
registry.destroy(obseletes.begin(), obseletes.end());
```
for some reason to dont get this assert I need to remove Obsolete component before destroying them ending up with this : 
```cpp
registry.view<Obsolete>().each([&registry](const auto entity, const Obsolete& )
{
	registry.remove<Obsolete>(entity);
	registry.destroy(entity);
});
```

**Comment by skypjack** [comment] 2019-06-13 04:03
I'm sorry but I cannot consider this valid as it stands.

There are tests to verify the `destroy` function. While I know they could not be enough to catch all the corner cases, I need a small example to be able to reproduce the issue for my own.  
Otherwise, I'm allowed to think that it's due to the user code (eg a listener that destroys an entity during the destruction cycle or things like this one).

May I ask you to provide me with a small, complete snippet that suffers from the same problem?

Thanks.

**Comment by kwarkGorny** [comment] 2019-06-13 18:23
This example has same assert: 
```cpp
struct Obsolete {};
int main()
{
	entt::registry registry;
	auto entity = registry.create();
	registry.assign<Obsolete>(entity);
	auto obsoletes = registry.view<Obsolete>();
	registry.destroy(obsoletes.begin(), obsoletes.end());

	return 0;
}
```

**Comment by skypjack** [comment] 2019-06-13 20:08
That's good. Thank you.  
Can I ask you what version of EnTT are you using? `master`, `v3.0.0`, whatever... Thanks.

**Comment by kwarkGorny** [comment] 2019-06-13 20:34
I downloaded master from 12 may

**Comment by skypjack** [comment] 2019-06-14 07:36
This is interesting because I cannot reproduce it on `master`. The snippet you provided works just fine.  
I'll try to push it on appveyor during the weekend. If you could investigate it further, it would help.

**Comment by kwarkGorny** [comment] 2019-06-15 10:27
I tried also v3.0.0 same issue. I have prepered VS2019 project on https://github.com/kwarkGorny/EnttIssue where I setup everything. Also I go through debugger and I think this is what is happening :
```cpp
registry.view<Obsolete>(); 
```
is returning 
```cpp
static_cast<pool_type<Component> *>(pdata->pool.get())
```
after that we are taking iterators for it and pass it to registry.destroy which will call 
pdata.remove(*this, entity); which calls registry.pool<Component>()->remove(registry, entt);
and after that iterators we passed at destroys are invalidated so we get assert on : 
ENTT_ASSERT(std::all_of(first, last, [this](const auto entity) { return orphan(entity); }));
from std::all_of when we try to reference them

**Comment by skypjack** [comment] 2019-06-15 14:15
Do you mind if I change the title of the issue to reflect the actual problem?

**Comment by kwarkGorny** [comment] 2019-06-15 14:35
No problem

**Comment by skypjack** [comment] 2019-06-15 21:50
I think you're right. Iterators aren't invalidated during iterations because of the remove, but those are taken by copy and the original ones are no longer valid actually. Good point!  
To sum up, the range destroy doesn't work properly with iterators returned by a view/group.

I tried to figure out why tests don't fail on the CI and I found that they run in release mode on appveyor, therefore asserts are suppressed. See #263 for the details.

Thank you for pointing this out.  
You've just contributed to improve further the library! :wink:

**Comment by skypjack** [comment] 2019-06-16 21:58
Why did you close this issue? The commit that fixes the problem isn't on `master` yet.

**Comment by kwarkGorny** [comment] 2019-06-17 08:23
my bad sorry

**Comment by skypjack** [comment] 2019-06-17 08:27
Not a problem. I've seen it from mobile and guessed why. I've still to merge on `master` because I turned off the laptop after the push, that's all. :smile:  
Out of curiosity, did you try it? Does it work fine now?

Also thank you for pointing out the problem, really appreciated! :+1:

**Closed** 2019-06-17 20:14 UTC
Labels: bug
