### ISSUE TITLE
Question: How to copy ECS data and later overwrite EnTT with that formerly copied ECS data?

### ISSUE THREAD

**Issue by DragonJawad** [skypjack/entt#818] opened 2021-12-28 17:04 UTC
*This question-issue is a follow up from [this Reddit thread](https://www.reddit.com/r/gamedev/comments/rlebqq/comment/hq04pvf/?utm_source=share&utm_medium=web2x&context=3)*

This question has two parts:
1. **Snapshot creation**: With ECS aspect of EnTT, how would one memcpy in an efficient manner all relevant data? (ie, how to efficiently create an ECS snapshot?)
2. **Snapshot restoration**: Later on, how would one write back that snapshot (copy of ECS data) back to EnTT? (ie, how to rollback state to that snapshot)?

### Additional Context
I'm looking to implement rollback features to my game- the ability to store game state for a specific frame and later on return to that state, which is particularly useful for fighting games with rollback netcode. Specifically, I'm worried about efficiently copying (and re-applying) that snapshot with EnTT, as the [snapshot section of the wiki](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#snapshot-complete-vs-continuous) depicts a relatively slow but straightforward approach to create such a snapshot.

I absolutely love EnTT but thought there were no quicker alternatives available here. Fortunately, according to [this conversation on Reddit](https://www.reddit.com/r/gamedev/comments/rlebqq/comment/hpkgzj1/?utm_source=share&utm_medium=web2x&context=3), there does seem to be a way to simply memcpy the relevant underlying ECS data from EnTT (and then later on overwrite existing ECS data from that formerly memcpy'd data).

However, after messing around with `entt::registry::storage(type_info)` and `entt::storage`, I'm still not certain what the intended way to use the existing EnTT implementation for this snapshot creation & restoration. **Could you provide examples on how to accomplish this with EnTT?**

Thank you for both the earlier help and for EnTT in general as well!

**Comment by Green-Sky** [comment] 2021-12-28 17:20
This is not a solution, but I recently discovered, that you can create multiple `storages` for the same type, effectively enabling double buffering (or more than double).
```
registry.storage<velocity>("previous snapshot"_hs);
```
https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#beam-me-up-registry

Hope this inspires some ideas.

**Comment by skypjack** [comment] 2021-12-29 15:31
Hi, the snapshot utility is actually pretty old and likely a good candidate for a review.
EnTT has changed **a lot** since when it was introduced. Moreover, it was implemented for a company with very strict requirements at the time. Therefore, it's not exactly a general purpose one.

If you want to go _raw_ and use something like `memcpy`, you must access the internal representation of a storage.
That is, you need to know how a storage works under the hood to get the best out of it. In this case, what matters most is that by default all storage classes are paged (you can change it actually but let's ignore this aspect for a moment).
Therefore, to serialize a single pool, you've to do something similar to the following:
```cpp
template<typename Type>
void serialize(entt::entity *entities, Type *components, entt::registry &registry) {
    auto &&storage = registry.storage<Type>(); // (1)
    const std::size_t page_size = entt::component_traits<Type>::page_size; // (2)
    memcpy(entities, storage.data(), sizeof(entt::entity) * storage.size()); // (3)

    for(std::size_t next{}, last = (storage.size() + page_size - 1u) / page_size; next < last; ++next) { // (4)
        const auto offset = next * page_size;
        memcpy(components + offset, storage.raw()[next], sizeof(component) * std::min(page_size, storage.size() - offset));
    }
}
```
In this case:
1. We get the underlying storage
2. We get the page size for the given type (you can set different sizes for different types)
3. We `memcpy` all entities at once in the destination buffer (entities are still fully packed)
4. We iterate all pages to also save the components (`page_size` of them at a time at once with the right offsets)

To restore a storage, the function is similar. You only have to provide the size from outside this time:
```cpp
template<typename Type>
void deserialize(std::size_t size, entt::entity *entities, Type *components, entt::registry &registry) {
    auto &&storage = registry.storage<Type>();
    const std::size_t page_size = entt::component_traits<Type>::page_size;
    storage.insert(entities, entities + size); // (1)

    for(std::size_t next{}, last = (storage.size() + page_size - 1u) / page_size; next < last; ++next) { // (2)
        const auto offset = next * page_size;
        memcpy(storage.raw()[next], components + offset, sizeof(component) * std::min(page_size, size - offset));
    }
}
```
What happens here is:
1. We insert all entities in the storage and get default constructed components for them
2. We copy the components a page at a time as we did during serialization

Deserializing would be easier if you had the arrays of entities and components already `memcpy`-ed in memory:
```cpp
storage.insert(entities, entities + size, components);
```
Of course, this mostly depends on your approach, so 🤷‍♂️ I'm just trying to give you a broader overview.
[This](https://godbolt.org/z/vK4TrGWs7) is an example that uses the functions above. I don't suggest using it in production because I don't guarantee that I haven't made any mistakes! 😂 

Also sorry if I don't go into it further but I'm technically on vacation at the moment. 😅
I'll be online again soon for any questions/concerns/suggestions to improve the approach.
However, I apologize in advance for the lag in the coming days.

**Comment by DragonJawad** [comment] 2021-12-29 17:46
Thank you for the solid explanation and thorough examples! It's really easy to understand how to put this into use straight away =)

I have one concern however- storage seems to be on a per-component basis. Thus, if I have say a 100 different types of components being actively used, then I have to memcpy at minimum a 100 times every time I want to serialize or deserialize the full snapshot.

Is there any way with the default storage to copy multiple components at once or would I need to define my own storage class in some fashion?

**Comment by skypjack** [comment] 2021-12-30 13:38
Storage classes are fully customizabe, so yes, you can define a storage that returns 1, 2 or 100 different types at once if you like, then use it with a view or whatever as any other storage.
However, I don't fully get your concern. If you had to copy 100 instances for 100 types with average size N, the amount of data you're going to copy would be exactly the same no matter what. Actually, standalone storage classes make it even easier to parallelize the process probably.
I'm pretty sure I've missed something of your reasoning, so feel free to elaborate on it. 👍🙏

**Comment by DragonJawad** [comment] 2021-12-30 22:20
Hmm... perhaps I'm overthinking this, but my concerns are efficiency and long term complexity.

Simplest case to compare is a single memcpy for all data for snapshot creation and restoration/serialization and deserialization.
- **Performance**: Simple case is most certainly faster, but up in air how much faster vs multi-threaded scenario  of 100 components in reality (where I'm not at just yet). Thus, assuming the multi-threaded scenario isn't too slow (eg, over 1ms), I'll be putting aside this performance concern for now as it's quite vague and arbitrary
- **Future use cases:** I was typing a whole lot here for some idealistic future use cases (eg, easy replay seeking by storing snapshot every, say, 0.5 seconds), but there aren't any real problems here. Yes it'll be a _tad_ bit more complex to preferably store the data in one place or such, but it's not a big deal either way. Thus, no issue here either =)

Really, I've just been overly worried for no reason as my FG rollback implementing peers typically just use a straightforward memcpy and I wanted to similarly have as tight of a performance as possible due to the inherent worse performance I already have with my 3D game. Without implementing and testing this - especially once the game I'm working on is much further developed - I can't say that this won't be sufficient at all.

Thus, I should be good to go ahead with this approach without customizing the storage class or such. Thank you for prodding me to write out my thoughts, as I was definitely overthinking things here once again ^_^

And once again as well, thank you for this amazing library- it's actually a legit joy to use and so happy there's no need to switch to a different library!

**Comment by skypjack** [comment] 2021-12-31 14:08
If you don't mind, I want to re-open this issue to keep track of some changes I'm working on.
After our discussion, I've realized how much we can improve the `insert` of a storage and how to make it fully opaque.
Just a boost you'll have in future for free, since I don't plan to change the API. 🙂 
I'll close the issue when these changes land on `master`. 👍

**Comment by DragonJawad** [comment] 2022-01-01 06:59
Thank you for planning to improve the `insert`- I really appreciate it! ^_^

As for this issue as a whole, I do have some good news and bad news (bug?). 

Good news is that your approach works pretty much perfectly for snapshot creation and restoration, AND the solution is pretty darn fast pre-multi-threading with 23 classes and ~100 components total. Was definitely overthinking the performance concerns earlier =)

In case it helps anyone: 
- [Gist with snapshot creation and restoration code in practice](https://gist.github.com/DragonJawad/b82c3d46ea9f3c310cb74feb1987b025)

However, the bad news is that `entt::registry` is unfortunately treating prior entity ids as invalid. I noticed this as I have a "spawn" system which keeps track of prior entity ids, checks if registry states any of them are invalid, and if so creates a new entity. This then leads to some related issues overall (including a crash on subsequent snapshot creation related to a component with a callback [invalid memory access]),

Component:
```
struct SpawnVolumeComponent {
    std::vector<entt::entity> spawnedEntities;
    Collider bounds;

    SpawnVolumeComponent() {} // Default ctor necessary for standard component initialization with std::vector
    SpawnVolumeComponent(const Collider& inBounds) : bounds(inBounds) {}
};
```

Related spawn system code which helped identify this issue:
```
void removeDestroyedEntities(entt::registry& registry, SpawnVolumeComponent& spawnVolumeComp) {
    // Stop tracking spawned entities that are no longer "valid" (ie, removed from the registry)
    auto newEnd = std::remove_if(spawnVolumeComp.spawnedEntities.begin(), spawnVolumeComp.spawnedEntities.end(),
                                [&registry](const auto& entityId) {                                   
                                    return !registry.valid(entityId);
                                });
    spawnVolumeComp.spawnedEntities.erase(newEnd, spawnVolumeComp.spawnedEntities.end());
}
```

Given the snapshot creation and restoration code backs up the entity ids - and in order - I'd expect the `entt::entity` to stay "valid" after the snapshot restoration.

I'm double checking more of my code as well before diving into EnTT code, but to double check: Is the above situation expected? **Is it "intended" for entity ids to be invalid after restoration?**

Oh, and happy new year! 🎉

**Comment by Green-Sky** [comment] 2022-01-01 13:19
entt reuses ids. ids have a version and a entity part and the version part gets incremented after a deletion and creation. I had a similar problem recently and i my hack consists of: deleting all components, tagging it with a special tag (empty component) and only ever actually deleting it, after i am sure i dont have to restore it. not sure how else to deal with this....

**Comment by skypjack** [comment] 2022-01-01 14:28
Happy New Year to you too!! 🥳 

Let me give you some context to explain this.
`EnTT` is slightly moving towards a model where using a registry isn't strictly necessary. Actually, this is possible already but I'm working to make it easier and easier over time.
Therefore, injecting entities and components into your storage classes isn't enough to let the registry know that those entities exist.

What you want is to also _save_ all entities and the implicit list of destroyed elements aside probably:
```cpp
    std::size_t sz = registry.size();
    entt::entity released = registry.released();
    entt::entity entities[count];
    memcpy(entities, registry.data(), sizeof(entt::entity) * sz);
```
Then restore them into the registry before using it:
```cpp
registry.assign(entities, entities + sz, released);
```
Now the registry _knows_ what identifiers are valid and what are not. [This](https://godbolt.org/z/aTKhKhvY7) is my first snippet once updated accordingly. 👍 
Let me know if you've any doubts or if this is unclear.

**Comment by DragonJawad** [comment] 2022-01-01 23:57
Odd, I'm still running into similar issues after implementing the save entities method as you outlined. Specifically, after creation -> restoring (or sometimes after creation -> restoration -> creation), I get the same issue again where the previously stored entity id is computed to be invalid.

Question regarding the `entt::registry::released()` method: 
Is this functionally a list of tombstoned entities in memory? If so, wouldn't the `released` value/list be invalid after the original registry is modified (eg, after a certain amount of time where the registry is modified compared to the snapshot or when recreating the registry as in the example `registry = {};`)?

On a different note:
Even if I turn off the relevant functionality that uses a previously stored entity id (the spawn system), then I unfortunately still get a crash due to a component with a callback being created with invalid memory. Thus, there may be two separate issues here (and on second thought, I really shouldn't be storing callbacks/pointers in components but theorizing that's not an issue just yet here).

**Comment by skypjack** [comment] 2022-01-02 15:01
`released` returns the _head_ of an implicit list of deleted entities.
Maybe I didn't understand what you are doing? My example resurrects an empty registry from scratch. In this case, you don't have invalid entities since you're also recreating them.
Are you doing something different? An example that shows what's wrong would help. An invalid id may be i.e. the result of restoring a pool in a registry where entities have been destroyed and recreated over time, without refreshing the list of entities.

**Comment by DragonJawad** [comment] 2022-01-03 00:14
Depends on what you mean by "different", here's the [updated gist with my snapshot specific code only](https://gist.github.com/DragonJawad/b82c3d46ea9f3c310cb74feb1987b025).

In short, my steps are as follows:

- On game startup, certain entities are created (~39 colliders for static level objects and various components for player and the one spawned enemy)
- On frame X (whenever I press a specific button), the snapshot is created
- Between snapshot creation and restoration, entities _may_ be destroyed, but in this basic testing I'm just moving around (so only modifying existing entities/components and not destroying anything)
- On frame Y some time later (whenever I press the button again), the snapshot is restored
- After restoration, the spawn system I mentioned in a couple comments ago checks its list of enemy entity ids (which there's only one in this context) to see if they're "invalid" according to the registry, and if so, spawns a new enemy. I have a log statement here to verify that the previous enemy entity id is treated by the registry as invalid after the snapshot restoration is complete

If `released` represents the head of an implicit list of deleted entities, then when the original registry is destroyed wouldn't that list thereafter be invalid? Would the full list need to be copied over before registry recreation?

Albeit based on what you said, there aren't really any released entities in this context and so the above isn't really the issue here. Hmm...

**Comment by skypjack** [comment] 2022-01-03 07:23
Great, I'll give it a shot as soon as possible. Sorry if I don't do it right away but I'm back at work today and I'm a little busy after vacation. 😅 
I'll try to give you a feedback on your snippet later today or tomorrow morning in the worst case. In the meantime, the faster insert is almost ready (testing it and adding a few other functionalities aside it).

**Comment by skypjack** [comment] 2022-01-05 07:48
Hi, sorry for the late reply.
I've looked into the your snippet and I've had to adapt it to make a working example. Unfortunately, I'm not able to reproduce your issue.
I've re-read the discussion and have a couple of questions though:
* The most obvious one is: are you able to pack a small, working example that reproduces your problem? It would help a lot to investigate and tell you what's wrong.
* As for the following instead:

  > However, the bad news is that entt::registry is unfortunately treating prior entity ids as invalid. I noticed this as I have a "spawn" system which keeps track of prior entity ids, checks if registry states any of them are invalid, and if so creates a new entity.

  Maybe I've misunderstood your problem. If I get it correctly, you've a system that stores aside a list of entities and _does something with them_. Then, some of these ids are invalid when you restore the snapshot. Is it correct?
  Let's consider this. When you take the snapshot, your system has ids (entity/version) `[1/0,2/7,3/1]` in its list. Then the simulation keeps running and you delete and recycle id 2. Therefore, it's returned as 2/8 (entity 2, version 8), that is a completely different id. Your system also intercepts it for some reasons and the list is now `[1/0,2/8,3/1]`.
  All of a sudden, you decide to restore the snapshot. Within the registry, you're recreating the old list of ids. Entity 2 will have version 7 in this case.
  When your system _tests_ its own list, it finds that `2/8` is invalid as it ought to be. If this is the issue, then... well, it's expected, since the list owned by the system wasn't snapshotted and is based on a (future) representation of your data that is no longer valid.

The first bullet is particularly useful to find what's wrong. However, please let me know if the second bullet correctly describes what's happening in your simulation.
Remember that ids are destroyed and reused with different versions over time. Therefore, if you store them aside, you should probably snapshot these lists too. Otherwise, it goes without saying that they risk to become invalid after a reload.
Another trivial example is this: the registry has ids up to N. You create a snapshot, then a new entity that the system puts aside in its list. If you restore the snapshot, the last id doesn't exist for obvious reasons. The system has an invalid entity to handle now. 🤷‍♂️ 

Does it make sense to you? Maybe it's a matter of expectations and you wanted something different?
Just to be clear, all my suggestions where meant to create a snapshot of a registry at a fixed point in time and to restore it as a whole a little later. For example, this doesn't work if what you want is to restore the data for the existing elements only while keeping the components for the newly created ids intact as well.

**Comment by DragonJawad** [comment] 2022-01-07 21:11
Apologies for my slow response, I've been quite sick this week after getting my booster shot =)

On topic here: Thank you very much for the simplified test suggestion, as it pointed out I was missing something VERY simple.
- [Gist for full test (using Google Test)](https://gist.github.com/DragonJawad/3cdda250aeb375f36ee4e9c899bbbf84)

With the snapshot creation and restoration process you outlined, everything works *perfectly* fine. My issue was that `std::vector` is effectively a wrapper around a pointer and thus I can't simply memcpy it. 

Surprisingly that didn't immediately cause issues in Unreal (guessing due to the fact that Unreal hijacks memory management completely and I'm hoping hasn't actually messed with standard containers), but thankfully `entt::registry::valid` was there to point out t hat the entity id given to it was, in fact, not valid

Thanks again for all the back and forth on this! 😄

**Comment by skypjack** [comment] 2022-01-08 12:51
Great! I'm glad to know that it worked. Let me know if you spot any other problems. 👍

**Comment by chengts95** [comment] 2022-01-10 04:34
Is it possible to have a runtime version of registry::storage? I am wondering is there a way to build a registry with the same pools of types without knowing the types at the compile time.

**Comment by skypjack** [comment] 2022-01-10 07:23
@chengts95 yup, working towards it. I've added a type-less `storage` to the registry and I'm adding an opaque `insert` aside a sort of _get all_ functionality to the storage base class. I only need to figure out how to implicitly create the pool in the target registry, since pools know nothing about the registry (and this isn't going to change any time soon).

**Comment by sunbubble** [comment] 2022-01-10 08:32
> With the snapshot creation and restoration process you outlined, everything works perfectly fine. My issue was that std::vector is effectively a wrapper around a pointer and thus I can't simply memcpy it.

I would hope that you can have a generic working solution using `std::copy` instead of `memcpy`. There's some references that `std::copy` becomes optimised to bulk copy operations for `TriviallyCopyable` types. https://en.cppreference.com/w/cpp/algorithm/copy

**Comment by chengts95** [comment] 2022-01-11 01:23
> @chengts95 yup, working towards it. I've added a type-less `storage` to the registry and I'm adding an opaque `insert` aside a sort of _get all_ functionality to the storage base class. I only need to figure out how to implicitly create the pool in the target registry, since pools know nothing about the registry (and this isn't going to change any time soon).

That is good news. By the way, the poly storage unit test should be deleted since it refers to deleted headers.

**Comment by skypjack** [comment] 2022-01-11 07:14
Oh. Good catch. Thanks for pointing it out. 👍

**Comment by skypjack** [comment] 2022-01-14 22:56
I close this as I don't need this memo anymore for the insertion function 😅 and I also think the original question was answered.
Feel free to reopen the issue if this isn't the case. Also thanks for the interesting discussion so far. 👍

**Closed by skypjack** 2022-01-14 22:56 UTC
Labels: question
