### ISSUE TITLE
Difficult to understand how it works without examples

### ISSUE THREAD

**Issue by MariwanJ** [skypjack/entt#1115] opened 2024-02-12 18:30 UTC
Thanks for this project, but the project needs real, usable example about several subjects of how  a beginner can use the library. 
if you have entities that you use often, you wouldn't choose to mix them with thousands of other entities. you make a group of these in keep track of them using a shared pointer. How would you do that here?
groups: how does they work.

Please, examples .. 

Just as an example of what I don't know how to solve it: 
`entt::basic_group cameras= m_Registry.view<Camera>();`
this doesn't work and I don't know how to delare cameras as a group of camera components.
BR

**Comment by skypjack** [comment] 2024-02-13 10:23
I mean, you can find how groups work and what their purpose is in the documentation. Have you already checked it? What you're trying to do tells me that you didn't probably.
In this case, I don't know how an example could help. You would never find an example regarding groups to do what you want and you would still open an issue saying that the examples are not clear.
The documentation is there for a reason. That's the first thing to read. Later, when we know what the tools are for, then an example can be useful. My two cents. 🤷‍♂️

**Comment by MariwanJ** [comment] 2024-02-13 11:39
Sorry, but documentation without examples is hard to read. For me, could be personal. I must see some examples before understanding the documentations. If you have time, please add some examples for each api you have. that will help a lot.

**Comment by skypjack** [comment] 2024-02-14 10:10
Yeah, I don't see how an example for the wrong tool can help.
You first need to read the documentation for that tool. Then you want to understand if it's a good fit for your problem. Finally, an example will tell you more about the API and the correct usage.
My gut feeling is that you don't know what a group is for. I can write thousands example but they won't help here. For example:

> this doesn't work and I don't know how to delare cameras as a group of camera components

Why do you think a group is the way to go? Perhaps because the name _group_ sounds quite close to what you would call the class you need? I strongly suspect EnTT groups are not what you're looking for because they do a different thing (carefully describred in the documentation).

Let's try a different approach. What problem are you facing? Can you describe it in details?
Once we know what you want to solve and understand what the right tool is, writing an example will be easier and faster than writing an example for a tool that isn't what you're looking for.

**Comment by skypjack** [comment] 2024-03-01 18:15
Adding examples is on the roadmap, no need to keep another issue around for that.
On the other side, I assume that the original problem was solved somehow since the issue is starving.
I'll close this issue as invalid but feel free to comment further if you have still problems. Thanks. 👍

**Closed** 2024-03-01 18:15 UTC
Labels: invalid
