### ISSUE TITLE
Implicit conversion from registry to view<T...>

### ISSUE THREAD

**Issue by BrodyHiggerson** [skypjack/entt#654] opened 2021-02-07 00:05 UTC
I've recently been playing around with a wrapper around the registry, as discussed elsewhere (on Discord etc), which prevents the user from directly accessing the registry, instead offering functions with the same signature as registry::view, with some static_asserts to ensure additional safety/constraints, particularly in the context of threading.

This approach exposed the need for utility functions to be able to accept either a registry& or one of these filters. Because the registry functions are templated, inheritance won't really work.

This made me realize - what if functions simply accepted views as arguments? It allows the functions to remain non-templated, and can conceptually accept any type as long as it can convert to a view.

```
// In some common header
using Entity = entt::entity;

template<typename... ComponentTypes>
using View = entt::basic_view<Entity, entt::exclude_t<>, ComponentTypes...>;

// Function decl example
SpaceID EntityToSpaceID(const View<const IDComponent>& view, Entity entity);
```
The above function can be called with anything that converts to entt view.

I'm sure I missed some edge cases, const, and handling of exclude lists, but this quick addition to the registry was a massive usability improvement in this scenario.

```
template<typename... Component>
operator basic_view<entity, exclude_t<>, Component...>() {
	return view<Component...>();
}
```

I'm not sure if it is actually possible to implicitly convert to a view that specifies an exclude list, or if that's common enough as a use-case to bother. But imagine the previous function decl was more like this (I _think_ this is how you'd write it).
```
SpaceID EntityToSpaceID(const entt::basic_view<entt::entity, entt::exclude_t<Unwanted>, const IDComponent>& view, Entity entity);
```
The implicit conversion wouldn't work. But... who really needs that? I can imagine instead performing the exclude inside the function, maybe using the `|` operator to combine in an exclude-based view?

Thoughts?

**Comment by skypjack** [comment] 2021-02-07 16:08
Isn't it the same as `entt::as_view`?

**Comment by skypjack** [comment] 2021-02-09 07:35
Ping. 😄 
I think `as_view` already does what you want, so I'm tempted to close the issue.
Any comment or feedback? Here it is an example from the tests:
```
([](entt::view<entt::exclude_t<int>, const char, double>) {})(entt::as_view{registry});
```
As you can see, it create an object that is convertible to a view and that also supports exclusion lists.
It supports both const and non-const registries. The _constness_ is encoded in the template parameter.

**Comment by BrodyHiggerson** [comment] 2021-02-09 12:09
Interesting. `as_view` could work. It would simplify things if the registry itself could be converted implicitly - you can then start using various registry wrappers, mock registries, whatever, and let each of them construct the view however they need in order to do the implicit conversion. 

Whereas right now, if you're using template code that takes any registry-like type that can produce/convert to a view, you need to somehow do a `constexpr if` to only use `entt::as_view` for the registry, and some other conversion function for a different type. But if implicit conversions worked, it doesn't matter. You can just use whatever type it is and it will convert to a view. From an API usage PoV, at least on the user side, the implicit seems much simpler. Are there any dangers or downsides to that?

**Comment by skypjack** [comment] 2021-02-09 14:05
I don't remember why the conversion has itw own tool and isn't part of the registry API.
My gut feeling is that it was a design choice, mainly because I don't yet feel that a registry should _convert_ to a view or anything else.
Not sure I get exactly what the problem is with it. It seems fine to me, but I've also never inherited from a registry, so probably I'm missing something here?

**Comment by BrodyHiggerson** [comment] 2021-02-09 14:21
It's not so much literal inheritance, but rather; it is nice to be able to use wrapped registries and registries interchangeably. But if it is required to use entt::as_view for constructing a view from a registry (which is really all the operator does), then you can't use them interchangeably.

The syntax/names are probably not right, but something like this:

```
void Foo(const view<A, B>& view)
{
	
}

template<typename RegistryLike>
void Bar(RegistryLike& reg)
{
	// if we have the operator - anything that can make a view can do so easily
	Bar(reg);
	
	//////////////////////////////////////////////////////////
	
	// if we don't have the operator - we need to handle registry special case
	if constexpr (std::is_same_v<reg, entt::registry>)
	{
		Bar(entt::as_view(reg));
	}
	else
	{
		// User-created registry wrapper can easily build a view
		Bar(reg);
	}
}
```
But I also feel like it simplifies trying to construct functionality out of callable/reusable functions. Ignoring the above advantages (both in template code and in non-template code where it is at least a bit simpler instead of having to use as_view) - it makes it 'nicer' imo to build your functionality out of functions which accept views - the registry is just another view-creating object that you can use, alongside whatever wrappers you need to control access on top of that.

```
void DoStuffA(const view<FooComponent, A>& view) {}
//etc ...
void DoStuffZ(const view<FooComponent, Z, BarComponent>& view) {}

// Some user-code customization/wrapper for using registries
// - could be for guarding threaded access, could be in some test framework, etc
struct UserRegistryWrapper
{
	// ...	
	// has wrapped versions of view, get, etc
	// can also construct a view implicitly
	// ...
	
private:
	Registry* reg;
}

// User code is easy - we just construct a view whenever it's needed
void Update(const Registry& reg)
{
	DoStuffA(reg);
	
	// other code
	
	DoStuffB(reg);
	DoStuffC(reg);
	
	FOR thread in threads:
		// Wrap registry in some thread-guarding wrapper for this example
		UserRegistryWrapper wrapped{reg};
		
		DoStuffD(wrapped);
		DoStuffE(wrapped);
		
		// other code
		
		DoStuffF(wrapped);
		
	DoStuffZ(reg);
}
```

**Comment by skypjack** [comment] 2021-02-10 15:20
If `RegistryLike` inherits from `registry`, `as_view` works just fine. I guess the problem is that you wrap it but don't really expose it to the user? Maybe an `operator registry &()` can solve the problem without changing the library. Or we could make `as_view` work with registry-like types rather than registry-only types.
I don't like the idea of adding conversion operators to the registry though. It seems... odd to me.  Let me think a little to it or try to convince me with better arguments. 🙂

**Comment by Innokentiy-Alaytsev** [comment] 2021-02-11 07:02
What about specialising `as_view()` for your types and (probably) using it through ADL?

**Comment by skypjack** [comment] 2021-02-11 07:57
It's not a plain function @Innokentiy-Alaytsev so ADL may be a pain in this case.
As for the specialization, it may work but it only has the entity type as template parameter at the moment.

**Comment by Innokentiy-Alaytsev** [comment] 2021-02-11 08:04
Is transforming `struct as_view` to `struct as_view_t` and declaring `as_view` as a function an option?

**Comment by skypjack** [comment] 2021-02-11 08:15
I don't think so, because `as_view` deduces the type of the view by means of a templated conversion operator.
If we turned it in a function, we would has to specify explictly the type of the view and this defeats completely its purpose.

**Comment by skypjack** [comment] 2021-02-19 09:12
I'm wondering if I should close this issue or not.
I won't add conversion functions to the registry and I didn't understand if the request became to do something for `as_view`/`as_group`.
At a first glance, the current design supports the vast majority of cases. Imho there is nothing to do here. Any feedback?

**Comment by BrodyHiggerson** [comment] 2021-02-20 03:29
My main question is; there must be some big downsides to this idea, right? I'm curious what they are, in case I'm exposing myself to some big risk by adding it in a fork. It feels like a good usability improvement to me, like in the example code proposed above. But if there is strong opposition, so be it. I'd just like to know why :)

**Comment by skypjack** [comment] 2021-02-21 15:03
As I said, my gut feeling is that these conversion operators shouldn't be part of the registry, that is also why an `as_view` utility exists. Also, if the goal is to inherit from a registry to set constraints on types, it wouldn't really help. Instead, it would be a perfect way to get around them. No?
Anyway, other than that and probably more important reason, I'm thinking of changing the way we construct views because of other feature I want to introduce. Briefly, it will be `view<T...> my_view{tegistry}`. Shouldn't it solve your problem at the root?

**Comment by skypjack** [comment] 2021-05-16 20:41
@BrodyHiggerson if you agree, I'd close the issue. The reason is simple (and in the TODO list too). 🙂 
It's a matter of time, but I'll flip the view creation on its head and make views receive a registry to their constructor.
So, you don't really need a conversion operator and you'll be able to _assign_ a registry to a view on construction in any case.

**Comment by skypjack** [comment] 2021-05-18 07:24
I guess it's a - _yes, please, do it_. 😄 
Feel free to reopen if I'm wrong. 😉

**Closed by skypjack** 2021-05-18 07:24 UTC
Labels: triage
