### ISSUE TITLE
entt symbols are not exported with MinGW64

### ISSUE THREAD

**Issue by ElDesalmado** [skypjack/entt#719] opened 2021-06-23 14:52 UTC
When exporting symbols from an executable with MinGW64 on Windows nothing is exported.  
The main reason is that class functions are implemented within classes, for example:
```
struct ENTT_API type_seq final {
    [[nodiscard]] static id_type next() ENTT_NOEXCEPT {
        static ENTT_MAYBE_ATOMIC(id_type) value{};
        return value++;
    }
};
```
This SO [answer](https://stackoverflow.com/a/1444034/9363996) mentions, that:
> C++ functions implemented inside of a class declaration are automatically defined inline.

So there is an inconsistency (at least in MinGW64):
- for shared libraries the symbols are exported
- for executables the symbols are inlined and not exported 
- for executables and in-class implemented functions that are explicitly marked `dllexport` the symbols are also exported.

 I know that there are workarounds to just compile `entt` as a dll, or maybe set a `noinline` option , etc. But I really would like to avoid that.

For example, I have a core application that loads plugins, and those plugins are using symbols exported from the core executable.

**Comment by ElDesalmado** [comment] 2021-06-24 06:19
according to mingw documentation regarding `dllexport`: 
> When applied to C++ classes, the attribute marks defined non-inlined member functions and static data members as exports. Static consts initialized in-class are not marked unless they are also defined out-of-class.

It is not clear though what it implies about `non-inlined` functions: whether they are marked `inline` by user or inlined by compiler. 
I tried to compile a dll that includes `entt/entt.h`, but nothing is exported whatsoever.

**Comment by skypjack** [comment] 2021-06-24 07:29
Unfortunately, this stuff is not regulated by the standard. So, roughly speaking, it's chaos and nothing more. 😄 

> C++ functions implemented inside of a class declaration are automatically defined inline.

That's true. However, the dll export directive should inhibit the inlining for itself. That's how it works with all major compilers.
Out of curiosity, do you pass `ENTT_API_EXPORT` and `ENTT_API_IMPORT` during compilation? Otherwise `ENTT_API` isn't defined and this would explain the inlining. Also, have you tried the `-fvisibility` flag or equivalent with mingw?

**Comment by ElDesalmado** [comment] 2021-06-24 07:53
I compile core with `ENTT_API_EXPORT ` and plugins with `ENTT_API_IMPORT`. Though the symbols are not exported. If I explicitly mark class methods for `dllexport`, the symbols are exported. Also I opened a [bug report](https://sourceforge.net/p/mingw-w64/bugs/906/).

**Comment by skypjack** [comment] 2021-06-24 08:11
Ironically, I remember that I had to move the dll export/import tag at class level because of an ICE with a version of MSVC.
So, honestly, I don't even know how to help here without risking to break existing code. It seems an idiosyncrasy of mingw but it's also the first time it's been reported.

**Comment by ElDesalmado** [comment] 2021-06-24 08:19
I suppose then I will fork for now and introduce some workaround macro explicitly for mingw... 
I am not sure though that I am doing it right. In the wiki it is mentioned that a meta context could be passed to a plugin. Does it mean that a plugin would use a pointer to to static variables within a core that exposes that meta context?

For now I have a code for a plugin that gets a pointer to the registry from the core. But gdb says that `type_seq::next()` used is within the dll, not the core.
```
#include "export_types.h"

extern "C"
{
    void initialize(const entt::registry* );
    void say_msg();
}

#include <iostream>

static const msg_struct *msgStruct = nullptr;

void initialize(const entt::registry *pRegistry)
{
    auto view = pRegistry->view<const msg_struct>();

    // if (!view.size_hint()) // does not compile: "has no member size_hint"
    if (!std::distance(view.begin(), view.end()))
    {
        std::cerr << "Plugin: no msg entities found!" << std::endl;
        return;
    }

    msgStruct = std::addressof(view.get<const msg_struct>(view.front()));
}

void say_msg()
{
    if (!msgStruct)
    {
        std::cerr << "Plugin: entity was not registered" << std::endl;
        return;
    }

    std::cout << msgStruct->msg << std::endl;
}
```

**Comment by ElDesalmado** [comment] 2021-06-24 09:50
The only valid solution to use symbols with one definition is to make a custom `impl.hpp` header that would include headers with implementations. If one would like to compile the lib as a standalone module,  one would include that source once in his `.cpp` file.

In [ASIO ](https://think-async.com/Asio/asio-1.18.2/doc/asio/using.html#asio.using.optional_separate_compilation) this looks like:
```
//
// impl/src.hpp
// ~~~~~~~~~~~~
//
// Copyright (c) 2003-2021 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#ifndef ASIO_IMPL_SRC_HPP
#define ASIO_IMPL_SRC_HPP

#define ASIO_SOURCE

#include "asio/detail/config.hpp"

#if defined(ASIO_HEADER_ONLY)
# error Do not compile Asio library source with ASIO_HEADER_ONLY defined
#endif

#include "asio/impl/error.ipp"
#include "asio/impl/error_code.ipp"
#include "asio/impl/execution_context.ipp"
#include "asio/impl/executor.ipp"
#include "asio/impl/handler_alloc_hook.ipp"
#include "asio/impl/io_context.ipp"
...
```

That, of course, means, there needs to be a series of implementation headers.

**Comment by skypjack** [comment] 2021-06-24 10:18
Honestly, I'd try to get why mingw behaves differently from everyone else rather than messing up the entire library to please it.
Also, what symbols are we talking about? If I understand correctly, only the id generator interests you, right?

**Comment by ElDesalmado** [comment] 2021-06-24 10:22
I am not sure that it is *the* only thing that interests me, maybe there are other symbols I am not aware of yet. 
The goal is to preserve the core ABI when adding new components (and not removing or modifying the existing), so the existing plugins would still work.

**Comment by ElDesalmado** [comment] 2021-06-24 13:54
I've checked with MSVC and debugger - the `type_seq::next` that is invoked from within the dynamically loaded plugin is found inside the core executable:
```
(lldb) image lookup --address 0x00007ff7f2cc97f0
      Address: sb.entt_core.exe[0x00000001400197f0] (sb.entt_core.exe...text + 100336)
      Summary: sb.entt_core.exe`entt::internal::type_seq::next() at type_info.hpp:26
```
That means that MSVC *does* export in-class implemented (inlined, I guess) functions and successfully imports them. 

I've decided to check with Clang. Just like MSVC it did exported symbols and created a static lib, which was successfully linked with plugins. I thought that it is indeed the MinGW, who misbehaves among the mainstream compilers. But nevertheless I checked the symbols. And I found out that it only *seem* to work. 

This is the address of a symbol when invoked from within the core exe:
```
(gdb) info sym 0x00007ff691b83010
entt::internal::type_seq::next() in section .text of C:\dev\repos\entt_test\cmake-build-debug-clang64\sb.entt_core.exe
```

But regardless of exported symbols and successful linkage, the plugin has violated ODR:
```
(gdb) info sym 0x00007ffc6d3a2170
entt::internal::type_seq::next() in section .text of C:\dev\repos\entt_test\cmake-build-debug-clang64\libsb.entt_plugin.dll
```

As you can see, MinGW is not the only one who needs to be pleased...

On the other hand, I don't see how a compiler would understand, that it does not have to compile a function for a plugin, when it sees that function has an inline implementation.

Consider this:
```
struct __declspec(dllimport) type_seq final {
    [[nodiscard]] static id_type next() ENTT_NOEXCEPT {
        static ENTT_MAYBE_ATOMIC(id_type) value{};
        return value++;
    }
};
```
How is a compiler to know, that `next()` need not to be compiled? My wild guess is that it **does** compile the definition for `type_seq::next()`. And eventually it works because the linker **maybe** eliminates duplicated symbols.  
The only way to check it is to look inside `.obj` files for identical symbols. If this is the case, I think separating implementation from declaration to different headers would be inevitable if one would want to share symbols across modules.

**Comment by skypjack** [comment] 2021-06-24 15:06
Technically speaking, no one violates the ODR here since the standard doesn't take in consideration the fact that we use libraries in the real world and therefore it doesn't rule about them. 😄 

Anyway, from your description I don't get if you're linking to the main executable or blindly loading a plugin. Those are very different cases and ask for different approaches. In any case, the `lib` dir contains examples for all them and I'm pretty sure that things work as expected with all major compilers (that is, the ones supported by this library, but I can't speak for mingw honestly, even though it seems on the wrong side of the fence here).
My suspect is that you're hitting that infamous problem due to static stuff which is not regulated by the standard and hasn't a common behavior on all platforms. If this is the case, things should change soon as mentioned [here](https://github.com/skypjack/entt/issues/714#issuecomment-862994428) since I plan to switch to a static-less solution. In the meantime, you can use a [type context map](https://github.com/skypjack/entt/blob/master/test/lib/registry_plugin/type_context.h) as pointed out in the same comment (or any other solution that centralizes the id generation, direct indexing is still faster than name based lookups and that's why I'm spending lot of time to find the best approach so as not to sacrifice performance).

> On the other hand, I don't see how a compiler would understand, that it does not have to compile a function for a plugin, when it sees that function has an inline implementation.

The compiler doesn't really care about it. The linker discards a symbol eventually. Otherwise all sides of a boundary will have their own copy of a static variable or whatever. That's how things work on all platforms. What changes is usually the default visibility and whatnot.

> I think separating implementation from declaration to different headers would be inevitable if one would want to share symbols across modules.

It won't be because you would have to mark the external implementations as inline to guarantee backward compatibility. So, the next step would be to make an optional `ENTT_INLINE` tag or similar to also disable it on need.
In any case, all this won't solve any issue because, yeah, things just work across boundaries already and in many projects, so probably the issue isn't that we need to split them. On the other side, it will complicate everything by several order of magnitude and make the whole thing very hard to maintain and to extend.
Therefore, I don't think this will happen any time soon. I'm sorry. 🙂

**Comment by ElDesalmado** [comment] 2021-06-30 12:15
After a fair amount of attempts and research I figured out the way to make it work with MinGW64.  
Basically one has to create a shared library with exported symbols. Something like:
```
// export_types.cpp
#include "export_types.h"

template struct entt::type_seq<bar_0>;
template struct entt::type_seq<msg_struct>;

// export_types.h
#pragma once

#include <entt/entt.hpp>

struct bar_0{};

struct msg_struct
{
    char msg[256]{};
};
extern template struct entt::type_seq<bar_0>;
extern template struct entt::type_seq<msg_struct>;
```

In this case it **does** work with MinGW64 and Clang.  However, MSVC will fail:
When compiling export lib I get warnings:
```
[ 50%] Building CXX object original/CMakeFiles/export_lib.dir/export_lib.cpp.obj
export_lib.cpp
C:\dev\repos\entt_test\original\export_types.h(14): warning C4910: 'entt::type_seq<bar_0,void>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation
C:\dev\repos\entt_test\original\export_types.h(15): warning C4910: 'entt::type_seq<msg_struct,void>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation
[100%] Linking CXX shared library export_lib.dll
[100%] Built target export_lib
```

When trying to link a plugin against exported lib, I get unresolved symbols:
```
LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\sb.entt_plugin_original.dir\objects1.rsp /out:sb.entt_plugin_original.dll /implib:sb.entt_plugin_original.lib /pdb:C:\dev\repos\entt_test\cmake-build-debug-visual-studio\original\sb.entt_plugin_original.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL export_lib.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\sb.entt_plugin_original.dir/intermediate.manifest CMakeFiles\sb.entt_plugin_original.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library sb.entt_plugin_original.lib and object sb.entt_plugin_original.exp
plugin.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static unsigned int __cdecl entt::type_seq<class entt::sigh_storage_mixin<class entt::basic_storage<enum entt::entity,struct msg_struct,class std::allocator<struct msg_struct>,void> >,void>::value(void)" (__imp_?value@?$type_seq@V?$sigh_storage_mixin@V?$basic_storage@W4entity@entt@@Umsg_struct@@V?$allocator@Umsg_struct@@@std@@X@entt@@@entt@@X@entt@@SAIXZ) referenced in function "class entt::type_info __cdecl entt::type_id<class entt::sigh_storage_mixin<class entt::basic_storage<enum entt::entity,struct msg_struct,class std::allocator<struct msg_struct>,void> > >(void)" (??$type_id@V?$sigh_storage_mixin@V?$basic_storage@W4entity@entt@@Umsg_struct@@V?$allocator@Umsg_struct@@@std@@X@entt@@@entt@@@entt@@YA?AVtype_info@0@XZ)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: static unsigned int __cdecl entt::type_seq<struct msg_struct,void>::value(void)" (__imp_?value@?$type_seq@Umsg_struct@@X@entt@@SAIXZ)
sb.entt_plugin_original.dll : fatal error LNK1120: 1 unresolved externals
```

So far this way is not really portable on Windows (on Ubuntu everything works fine).  

Another way I thought of was to link directly against an exporting executable, but on windows it is problematic (MinGW allows direct linkage to dll without a static lib). I have a [question ](https://stackoverflow.com/questions/68193246/multiple-definitions-when-linking-to-exe-with-mingw?noredirect=1#comment120524176_68193246) on SO about that.

**Comment by skypjack** [comment] 2021-06-30 13:17
Let's see what comes out from the SO question. Keep me posted please. Thanks.

**Comment by ElDesalmado** [comment] 2021-06-30 13:21
The question is important indeed. Since MinGW linker has another bug - it can create an empty import table when linked to an MSVC-compiled library (to import C functions). I faced it when tried to make a node js addon. You also have to link against a node core, which is an executable... If one could easily link directly against an executable it would solve all of those problems.

**Comment by ElDesalmado** [comment] 2021-06-30 16:45
I feel that you also would like to take a look at [this](https://stackoverflow.com/questions/68101661/windows-mingw64-does-not-export-member-static-or-not-functions-defined-within) SO question. As some people pointed out in the comments, implicitly inlined methods (in-class implementations) are not guaranteed to be exported at all. As a matter of fact, on Windows neither or MSVC Clang or MinGW64 has exported any of non-template in-class implemented methods.

When linking to a dll with exported types I can invoke 2 functions:
```
entt::type_seq<msg_type>::value(); // explicitly instantiated in exports dll
entt::internal::type_seq::next();
```

Explicitly instantiated template will in turn invoke `entt:internal::type_seq::next()` from within the dll. But direct invocation of `entt:internal::type_seq::next()` will be calling an entirely different symbol defined within the executable. This is because it **has never been exported** neither by Clang nor by MinGW.  So the compiler just generated new code for it. I suppose on Ubuntu the behavior will be the same.  

At the end of the day, everything will be working seemingly fine and as expected if nobody calls `entt::internal` functions directly.  They are `internal` for a reason, they are **not expected** to be called directly.  
However, this is rather fragile and you never know when something goes wrong. And it would be impossible to find out why.

Take a look at the SO question I've mentioned at the beginning of this comment.

**Comment by skypjack** [comment] 2021-07-01 12:19
What they say in the SO Q/A is right. Probably the expectation is wrong. A function declared inline is not guaranteed to be exported. On the other side, it's perfectly fine if you can see `type_seq<T>::value` and `internal::type_seq::next`, since they are marked to be exported. I would be worried if those symbols weren't visible.
Though, this is in contrast with what you said in the first comment:
> When exporting symbols from an executable with MinGW64 on Windows nothing is exported.

So, I'm now wondering what the case is (and I'd say it's the former, given that I'm happily exporting and using those functions on all platforms - granted, not mingw).

> However, this is rather fragile and you never know when something goes wrong. And it would be impossible to find out why.

I mean, if someone invokes a function explicitly marked as internal and something goes wrong, I don't think that the problem is in the fragility of a solution. It's likely on the other side of the monitor instead. 😅 
What would be the other way around. To turn off inlining and force all functions in the library to be exported? This has a (**huge**) cost under many aspects. It solves by far more problems than what it is meant to solve, especially if it meant to protect me from people who invoke internal functions of a header-only library.

**Comment by ElDesalmado** [comment] 2021-07-01 12:43
Take a look at this output for an exe or dll compiled with Clang on Windows (from my question):
````
Dump of file libapp.dll.a

File Type: LIBRARY

     Exports

       ordinal    name

                  _ZN5foo_tIiE3barEv
                  _ZN5foo_tIiE3buzEv
                  _ZN5foo_tIiEaSERKS0_
```

There are no `foo` symbols. That is `foo` is a non-template class marked for export with `__declspec(dllexport)` and in-class methods implementations. Just like non-template `entt:internal::type_seq`. 

Anyway, I don't think that rushing to solutions is a good idea. Now I have a working in an expected way code.  
I think I will add a test that proves or disproves my theory about non-exported symbols. You have all the CI needed to get the result immediately. Afterwards it will be clearer whether something needs to be and may done.

**Comment by ElDesalmado** [comment] 2021-07-08 07:11
At some point in time my "workaround" with `entt` as a shared library with exported explicit template instantiations failed to work. In Release with MinGW it does not pass my project's CI tests. So I think it is safe to say that my team is stuck :(   
I gave the problem some further investigation and have found out that linker optimization for importing symbols can optimize out those even if they have been exported. In some cases I have `entt::internal::type_seq` exported only in Debug, but not in Release, in other cases it is not imported in either configuration. For MSYS2 Clang64 the results differ in many ways then for MinGW64.  
So I added 3 tests in an attempt to expose implementation-dependent differences. I have succeeded to reproduce my problem for MinGW64: *increment test* is passed in Debug, but segfaults in Release.   

For MSYS2 Clang64 in Debug and Release the results differ from MinGW, but are consistent between configurations:
```
C:\dev\repos\entt\cmake-build-debug-clang64\test\lib\registry_shared_lib\importing_core.exe
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from shared_registry_lib
[ RUN      ] shared_registry_lib.compare_ids_within_core
../test/lib/registry_shared_lib/main.cpp:36: Failure
Expected equality of these values:
  entt::type_seq<test_increment>()
    Which is: 0
  1
[  FAILED  ] shared_registry_lib.compare_ids_within_core (0 ms)
[ RUN      ] shared_registry_lib.compare_ids_across_modules
../test/lib/registry_shared_lib/main.cpp:65: Failure
Expected equality of these values:
  pGetId()
    Which is: 0
  2
[  FAILED  ] shared_registry_lib.compare_ids_across_modules (0 ms)
[ RUN      ] shared_registry_lib.test_increment
[       OK ] shared_registry_lib.test_increment (0 ms)
[----------] 3 tests from shared_registry_lib (1 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] shared_registry_lib.compare_ids_within_core
[  FAILED  ] shared_registry_lib.compare_ids_across_modules

 2 FAILED TESTS

Process finished with exit code 1
```

Unfortunately, the github workflow does not run tests for MSYS2 Clang64 or MinGW64.

It is however, very interesting on GCC for Ubuntu. Despite the fact that all checks in github workflow for Linux have passed successfully (that was not what I expected), the test *did* fail on my colleague's Ubuntu `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` (I don't have it on my laptop):

Release:
```
/tmp/entt/cmake-build-release/test/lib/registry_shared_lib/importing_core --gtest_filter=shared_registry_lib.compare_ids_across_modules:shared_registry_lib/*.compare_ids_across_modules:*/shared_registry_lib.compare_ids_across_modules/*:*/shared_registry_lib/*.compare_ids_across_modules --gtest_color=no
Testing started at 10:52 ...
../test/lib/registry_shared_lib/main.cpp:65: Failure
Expected equality of these values:
  pGetId()
    Which is: 0
  2



Process finished with exit code 1
``` 

Debug:
```
/tmp/entt/cmake-build-debug/test/lib/registry_shared_lib/importing_core --gtest_filter=shared_registry_lib.compare_ids_across_modules:shared_registry_lib/*.compare_ids_across_modules:*/shared_registry_lib.compare_ids_across_modules/*:*/shared_registry_lib/*.compare_ids_across_modules --gtest_color=no
Testing started at 10:52 ...
../test/lib/registry_shared_lib/main.cpp:65: Failure
Expected equality of these values:
  pGetId()
    Which is: 1
  2



Process finished with exit code 1
```

As can be seen, both tests have failed but with different output. The more interesting fact is that for the first build in Release all the tests have passed. But the second and following attempts we could not reproduce it - failed each time.

As for MSVC - it will not compile...

**Comment by skypjack** [comment] 2021-07-08 11:16
> At some point in time my "workaround" with entt as a shared library with exported explicit template instantiations failed to work.

What workaround exactly? Not sure I know what you're talking about here.

> In Release with MinGW it does not pass my project's CI tests. So I think it is safe to say that my team is stuck :(

I'm sorry to hear this.

> I gave the problem some further investigation and have found out that linker optimization for importing symbols can optimize out those even if they have been exported.

The linker is a runtime thing, so this means that symbols are exported as it ought to be. No idea why it should optimize them out but can it be due to the fact that they aren't used on both sides of a boundary? Hard to say without looking at the code. 🤷‍♂️ 

> So I added 3 tests in an attempt to expose implementation-dependent differences. I have succeeded to reproduce my problem for MinGW64: increment test is passed in Debug, but segfaults in Release.

Ahaaaa... the PR? Those tests are odd honestly. The non-linked one shows that `ENTT_API_*` stuff doesn't work and it's expected but it doesn't depend on EnTT, it's just that `declspec` and the others are meant for linked libraries.
The plugins are curious instead. They don't work but from what I can see in the code it's expected, so probably the problem was in the initial expectation? This or I'm missing some details, it wouldn't be the first time that I don't fully get something.

> As can be seen, both tests have failed but with different output. The more interesting fact is that for the first build in Release all the tests have passed. But the second and following attempts we could not reproduce it - failed each time.

Without a shared generator, it only depends on the execution flow. Yo ucan run it 1000 times and see it pass 500, 0, all times. All results would be fine.

> PS: should I post messages on the topic here or in PR thread?

This issue contains the whole story, so I would continue here (also helpful for future readers).

**Comment by hero2002** [comment] 2021-09-20 12:32
did you try the new version of mingw [here](https://github.com/brechtsanders/winlibs_mingw/releases/) I was having awkward problems with the old one

**Closed** 2021-12-13 08:04 UTC
Labels: enhancement, solved
