### ISSUE TITLE
Recent build changes break usage of User Package Registry

### ISSUE THREAD

**Issue by DonKult** [skypjack/entt#451] opened 2020-03-24 12:09 UTC
Hi,

in my toy project I import EnTT with
````
find_package(EnTT REQUIRED CONFIG)
target_link_libraries(${PROJECT_NAME} PRIVATE EnTT::EnTT)
````
and the help of the [User Package Registry](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#user-package-registry). This fails since 23e839b40e23f7aaaad4aefb5cce194e78d16ff6 with:
````
CMake Error at /path/to/entt/build/EnTTConfig.cmake:23 (message):
  File or directory /home/user/include referenced by variable
  ENTT_INCLUDE_DIRS does not exist !
Call Stack (most recent call first):
  /path/to/entt/build/EnTTConfig.cmake:39 (set_and_check)
  src/CMakeLists.txt:9 (find_package)
````
dropping the offending `set_and_check` line from `cmake/in/EnTTConfig.cmake.in` solves that as nothing seems to need `ENTT_INCLUDE_DIRS` after all.

Trying again gives me the next error:
````
CMake Error at /path/to/entt/build/EnTTConfig.cmake:40 (include):
  include could not find load file:

    /path/to/entt/build/EnTTTargets.cmake
Call Stack (most recent call first):
  src/CMakeLists.txt:9 (find_package)
````
This seems to be fixed by adding the following stanza in `CMakeLists.txt`:
````
export(
    EXPORT EnTTTargets
    FILE "${CMAKE_CURRENT_BINARY_DIR}/EnTTTargets.cmake"
    NAMESPACE EnTT::
)
````
which I adapted from [the example given in the cmake documentation](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages).

And with that my project compiles again. :tada:

I have quite literally no idea what I am doing though, cmake is akin to witchcraft for me.

**Comment by skypjack** [comment] 2020-03-24 21:55
>I have quite literally no idea what I am doing though, cmake is akin to witchcraft for me.

Yeah, removing a line here and adding a duplicate of an export doesn't look like the right solution actually. :smile: 
Can you provide a minimal example to reproduce the error? This way I can look directly into the issue.

Thank you.

**Comment by skypjack** [comment] 2020-03-24 23:57
I've updated the build system and tested it. Everything works as expected.
May I ask you to test branch `experimental` and report your errors if any?

Thanks.

**Comment by DonKult** [comment] 2020-03-25 16:50
Thanks for taking a look, but the issue remains with the exact same remedies – which isn't too surprising as I am not `make install` so `PACKAGE_CMAKE_INSTALL_INCLUDEDIR` probably doesn't contain something sensible (and I consider a may or may not existing include/ dir in my home directory as not sensible). And the `export(EXPORT …` is what is suggested in the [example in cmake docs](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages), so while I have no idea I have some hope that they know what they are doing.

As you asked for an example (assuming a linux machine), here we go:
````
git clone 'https://github.com/skypjack/entt'
cd entt && mkdir build && cd build
cmake -DUSE_LIBCPP=OFF -DBUILD_DOCS=OFF -DBUILD_TESTING=OFF -DFIND_GTEST_PACKAGE=ON ..
make
mkdir -p ~/.cmake/packages/EnTT
echo "$(pwd)" > ~/.cmake/packages/EnTT/buildpath
mkdir /tmp/toyproject && cd /tmp/toyproject
cat > CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.4.0)
project(toyproject VERSION 0.0.0 LANGUAGES CXX)
find_package(EnTT REQUIRED CONFIG)
add_executable(${PROJECT_NAME} main.cc)
target_link_libraries(${PROJECT_NAME} PRIVATE EnTT::EnTT)
EOF
cat > main.cc <<EOF
#include <entt/entity/registry.hpp>
int main() {
        return static_cast<int>(entt::registry{}.create());
}
EOF
mkdir build && cd build && cmake ..
````
(typos I made are all copyright me, everything else is free to use elsewhere :wink: )

**Comment by skypjack** [comment] 2020-03-25 17:04
>I am not `make install`

Ah.

>so `PACKAGE_CMAKE_INSTALL_INCLUDEDIR` probably doesn't contain something sensible

I must admit that I haven't even taken in consideration the case in which the library isn't properly installed, so yeah, it may be that this variable doesn't contain anything sensible actually.

>so while I have no idea I have some hope that they know what they are doing

The problem with their examples is that they are fragmented and they use a feature here, a fixed variable there, and so on. They are a good starting point but hardly the right solution for all cases.

>As you asked for an example (assuming a linux machine), here we go

That's good! I didn't get what you were doing and this example will help to wrap my head around your problem now that I got it.
Thank you very much for spending your time with this. Really appreciated. Let's reopen the issue and address also your case. :+1:

**Comment by skypjack** [comment] 2020-03-26 22:40
Aaaaaaaaand... I apologize.
I should have read more carefully your first message that seemed to me in conflict with the current install process.
I noticed... kind of... 10 minutes ago that you weren't adding a duplicate for the export clause. Instead, you were adding an export directive for the build tree.
So I picked out the commit in which I reviewed that part and realized that I removed too much. :smile: 

My fault and really thanks for insisting on this issue.

I'm cleaning up anyway the previous solution because another comment of yours triggered me:

>nothing seems to need ENTT_INCLUDE_DIRS after all

This isn't due to the fact that _nothing needs this variable_. We are exporting stuff, so it goes without saying that nothing in `EnTT` needs it.
Instead, the key part is that we are already exporting targets as a whole and you can link to include directories by linking to the targets rather than by using this variable. That is, this variable quicly becomes obsolete and is mainly targeted to a non-modern cmake model that `EnTT` isn't supporting at all.

Good catch and thank you again for making me reopen the issue and investigate further.
You contributed to make `EnTT` a better place for cmake users. :wink: :heart:

**Comment by skypjack** [comment] 2020-03-26 23:05
May I ask you to test branch `experimental`?

**Comment by DonKult** [comment] 2020-03-27 08:29
Can confirm that the `experimental` branch works for me™. :+1:

**Comment by skypjack** [comment] 2020-03-27 08:39
Thanks for testing and thank you again for insisting. :+1: :wink:

**Closed** 2020-03-27 22:21 UTC
Labels: build system
