### ISSUE TITLE
entt::any in_situ optimisation breaks pimpl using classes in registry context

### ISSUE THREAD

**Issue by DonKult** [skypjack/entt#656] opened 2021-02-10 17:05 UTC
Hi,

my playground was crashing on startup on a `this` null pointer after my last entt update and a quick bisect found 1912350cc68e538634a82fdd38569e9acf85680e to be the culprit.

To reproduce you can add the following test to `test/entt/entity/registry.cpp`:
```cpp
class pimpl {
    //uint64_t make,it,fat; // (1)
    class Private;
    std::unique_ptr<Private> d;
public:
    pimpl();
    pimpl(pimpl const &p) = delete;
    pimpl(pimpl &&p) noexcept;
    pimpl& operator=(pimpl const &p) = delete;
    pimpl& operator=(pimpl &&p) noexcept;
    ~pimpl();

    bool check() const;
};
class pimpl::Private {
    aggregate foo;
public:
    bool check() const { return this != nullptr; } // (3)
};
pimpl::pimpl() : d{std::make_unique<pimpl::Private>()} {}
pimpl::pimpl(pimpl &&p) noexcept = default;
pimpl& pimpl::operator=(pimpl &&p) noexcept = default;
pimpl::~pimpl() = default;
bool pimpl::check() const { return d->check(); }

TEST(Registry, ContextPimpl) {
    entt::registry registry;

    auto &p = registry.set<pimpl>();
    ASSERT_TRUE(p.check());
    registry.set<char>('a'); // (2)
    ASSERT_TRUE(p.check());
}
```
I hope you agree that the second assert should not fail… it succeeds either by commenting the `(2)` line [not a solution longterm…] or uncommenting the `(1)` line to disable the in_situ optimization (or reverting the mentioned commit obviously). Note that `(3)` will usually generate a compiler warning as `this` is not supposed to be a null pointer in well behaving C++  so a real test would probably be a bit more elaborate. I have hence not spent too much time on good names (the class using the pimpl idiom should probably not be named pimpl itself. ☺).

**Comment by skypjack** [comment] 2021-02-10 18:06
Not sure I get why the pointer is null. The object should be moved internally if needed.
Do you know what the root cause is for this, other than the offending commit?

**Comment by skypjack** [comment] 2021-02-11 09:26
Note that the test above passes on `experimental`. I can't reproduce the issue.

**Comment by DonKult** [comment] 2021-02-11 13:14
I can reproduce it on `experimental` still with gcc 10.2.1 and clang 11.0.1  both with libstdc++, but okay.

Regarding the references: Yes and no. If the class is "fat" entt::any stores it *somewhere* and contains a pointer which can be easy moved around on capacity change of whatever container is backing up ctx without disturbing the actual data location and hence the reference to it. In the "in_situ" slim class optimization with its use of placement new the data is stored inside entt::any though and so has to move with it calling move on the type itself invalidating the reference I was holding on to.

I am surprised as API wise they look reasonably distinct and comparable to assigning different components to an entity, but if that's how it is supposed to be okay. I would appreciate at least a comment around .set<> (and .unset<>) that it potentially invalidates references you have to other context variables as that looks like an implementation detail leaking out.

**Comment by skypjack** [comment] 2021-02-11 22:10
> I can reproduce it on experimental still with gcc 10.2.1 and clang 11.0.1 both with libstdc++, but okay.

Yeah, I don't doubt about it. I think it's a matter of implementation. The standard doesn't dictate on this.

> I am surprised as API wise they look reasonably distinct and comparable to assigning different components to an entity, but if that's how it is supposed to be okay.

No, well, it makes sense. I didn't immediately realize the consequences of this change.
The final goal was to _save_ some allocations if possible, to reduce the jumps in memory when accessign context variables.
Given the scope of these variables, this isn't really required though. I was working on a constructor of `any` to force dynamic allocations when required. It could be used for context variables internally.

**Comment by skypjack** [comment] 2021-02-20 15:12
Hi, it should work as expected on branch `experimental`.
Can I ask you to give it a try and let me know before merging on master? Thanks!

**Comment by DonKult** [comment] 2021-02-20 20:31
works for me™ with `experimental` :+1: 
(entt tests as well as my playground)

**Comment by skypjack** [comment] 2021-02-21 14:59
Great, thanks for testing it. I'm closing this issue then. Soon upstream.
Briefly, I added the possibility of setting the sbo storage size of an `entt::any` and used it in the registry.

**Closed by skypjack** 2021-02-21 14:59 UTC
Labels: triage
