### ISSUE TITLE
nvcc 'incomplete type is not allowed' compile error 

### ISSUE THREAD

**Issue by FeiZhu** [skypjack/entt#1082] opened 2023-10-19 04:23 UTC
I am using entt in my project which contains some cuda code. When some source file that references entt is compiled with nvcc, 'incomplete type is not allowed' error is reported in entt headers (node.hpp and meta.hpp).

After some investigating, I found that the sample code provided by entt triggers the same error if compiled by nvcc (save to a file with extension .cu).

It maybe an issue of nvcc, but does anybody know how to workaround it? Thanks!

Separate entt code with cuda code may be an option, but it enforces burden to developers.

<img width="516" alt="Screenshot 2023-10-19 at 12 22 43" src="https://github.com/skypjack/entt/assets/3875954/46b8de4f-316d-411a-bd3b-83ad6230e903">

**Comment by skypjack** [comment] 2023-10-19 12:19
What type is incomplete exactly? As far as I can tell, you've to include a header for a locally defined type.
This issue doesn't contain the code to reproduce the error nor the complete message. It's literally impossible to help.
I'm sorry.

**Comment by FeiZhu** [comment] 2023-10-20 00:56
> What type is incomplete exactly? As far as I can tell, you've to include a header for a locally defined type. This issue doesn't contain the code to reproduce the error nor the complete message. It's literally impossible to help. I'm sorry.

Thanks for the reply.

Simply saving the [sample code] (https://github.com/skypjack/entt#code-example) to a file with .cu extension and compiling it with nvcc will produce the error.

The incomplete types reported  are meta_any in node.hpp and meta_type in meta.hpp.

The header I included in my project is entt/meta/factory.hpp, where meta.hpp and node.hpp are included. 

meta_any referenced in node.hpp is defined in meta.hpp, and meta.hpp is included before node.hpp in factory.hpp, which should have compiled correctly but it's not the case for nvcc.

meta_type is forward declared at line 27 in meta.hpp, its constructor is called at line 494, and its full definition appears at line 1088. This should have triggered incomplete type error, but it compiles correctly by multiple compilers (gcc, msvc, clang) except nvcc.

Hopes I have described the issue clearly.

**Comment by skypjack** [comment] 2023-10-20 09:56
> The header I included in my project is entt/meta/factory.hpp, where meta.hpp and node.hpp are included.

I think I'm missing something. The example includes `entt.hpp` while you say that you're including something else. Which one is correct?

> Hopes I have described the issue clearly.

Sure thing. As far as I can tell, the current implementation is _correct_ (well, for some definition of _correct_ 😅 certainly one that is good for C++ at least). So, yeah, probably nvcc has a problem when resolving types because of its internals.
I can't really help here though because I can't reproduce the error easily at the moment. However, I'm open to suggestions if you find an easy fix that makes nvcc happy as well. 👍 

> The incomplete types reported are meta_any referenced in node.hpp and meta_type referenced in meta.hpp.
> [...]
> meta_type is forward declared at line 27 in meta.hpp, its constructor is called at line 494, and its full definition appears at line 1088. This should have triggered incomplete type error, but it compiles correctly by multiple compilers (gcc, msvc, clang) except nvcc.

I think you refer to `allow_cast`, right? That's a function template though. It's not instantiated until use with a proper type `T`. Therefore, when you **do** need a definition for `meta_type`, it's there for sure. The same goes for `meta_any` within `node.hpp`.
It really looks like an issue of the nvcc compiler that somehow wants complete types where it shouldn't (according to the C++ language at least).

**Comment by FeiZhu** [comment] 2023-10-21 02:16
> > The header I included in my project is entt/meta/factory.hpp, where meta.hpp and node.hpp are included.
> 
> I think I'm missing something. The example includes `entt.hpp` while you say that you're including something else. Which one is correct?

My code includes factory.hpp, but for simplicity of reproducing the error we could use the entt example code, which includes entt.hpp.

> So, yeah, probably nvcc has a problem when resolving types because of its internals.

Yes, it's probably an issue of nvcc. Currently I figured out a workaround by placing gpu code and entt code in separate files so that nvcc won't compile any entt code.

**Comment by skypjack** [comment] 2023-10-21 15:02
Sorry, I meant the line in `meta.hpp` but yeah, it doesn't really change anything anyway.
Unfortunately, I can't help you much. All major compilers accept this code as it's valid C++ one. Making it work with nvcc would require a huge refactor since nvcc doesn't fit the requirements of the language (at least from what I see here).
I don't plan to invest my time on this kind of things though, sorry. Especially if a workaround exists (and you found it, right?).

**Comment by FeiZhu** [comment] 2023-10-23 00:38
Thanks. Let's just wait for the update of nvcc. I'll close the issue.

**Closed** 2023-10-23 00:39 UTC
Labels: wontfix
