### ISSUE TITLE
Question: How do I copy one entity from one registry to another registry

### ISSUE THREAD

**Issue by DaOnlyOwner** [skypjack/entt#834] opened 2022-01-29 14:15 UTC
Hello

Right now it feels like a hacky solution, but I check wether one entity has a component and manually attach it to the copied entity by emplacing the component into the other registry.
I know that you can iterate through the storage and copy construct your elements this way. But I don't want to copy all entities, just one specific to another registry. 
How do I do that?

Thanks

**Comment by skypjack** [comment] 2022-01-29 14:53
Possible duplicate of #827 - I'd close this one and add a comment to the other issue eventually. Makes sense to you?

**Comment by DaOnlyOwner** [comment] 2022-01-29 21:13
Okay, makes sense, but I would be very happy if you added the comment as well ;)

**Comment by skypjack** [comment] 2022-01-30 16:14
I mean, my comments are literally there already, starting from [this one](https://github.com/skypjack/entt/issues/827#issuecomment-1013697795). 😅 
My suggestion was for you, if you want to add a comment after reading that thread and if something is unclear.

**Closed by skypjack** 2022-01-30 16:14 UTC
Labels: duplicate, question
