### ISSUE TITLE
Runtime generated components?

### ISSUE THREAD

**Issue by WireWhiz** [skypjack/entt#895] opened 2022-06-13 02:10 UTC
Hello, I'm currently looking into if I can replace a custom ECS framework I built for one of my projects with Entt. The main reason I built my own is that I need to be able to generate components at runtime. 
My current workflow is like this: First, create a list of variable types, then initialize an instance of a component definition class that figures out the required memory size and offset/padding for each variable, it also stores constructors/destructors if necessary. Then that definition can be used by the entity manager instead of a struct to create archetypes. 
Is this currently possible with the Entt reflection system? And if it is not could it be easily added in?

**Comment by skypjack** [comment] 2022-06-13 06:33
Before answering, let me ask thi: are component types known beforehand? I mean, when you say:

>  then initialize an instance of a component definition class that figures out the required memory size and offset/padding for each variable

Are you just trying to figure out what you want from a fixed set of known types (because, well, C++ is a strongly typed language, you know) or are you creating a _fake runtime type_ as it happens for example in a js engine?

**Comment by WireWhiz** [comment] 2022-06-13 07:26
The types that are going to be used for the component members are known at compile time. I use templates to create the types themselves, so it looks something like this:
```
        std::vector<std::unique_ptr<VirtualType>> members;
	members.push_back(std::make_unique<VirtualVariable<bool>>());
	members.push_back(std::make_unique<VirtualVariable<int32_t>>());
	members.push_back(std::make_unique<VirtualVariable<float>>());
	members.push_back(std::make_unique<VirtualVariable<std::string>>());

	ComponentDefinition component(members, "component id");
```

**Comment by skypjack** [comment] 2022-06-13 09:47
So, all your components have type `std::vector<std::unique_ptr<VirtualType>>`, right?
Kind of at least, for example type `T` that is a tiny wrapper around the vector above. Do I get it correctly?

**Comment by WireWhiz** [comment] 2022-06-13 16:50
Pretty much

**Comment by skypjack** [comment] 2022-06-14 06:43
You can create multiple pools of the same type using the `storage` function, as long as you give them a different _name_.

**Comment by WireWhiz** [comment] 2022-06-14 07:53
So it would be relatively simple to create components that only have one member, just a matter of creating a type for each one and then naming them at runtime with the storage system right? Would that mean that if I wanted to create components with multiple members I would need to have every combination of members that I wanted to support be defined in types at compile time?

**Comment by skypjack** [comment] 2022-06-14 08:10
🤔 Uhm, no, I'd rather create a bunch of named pools for `std::vector<std::unique_ptr<VirtualType>>`.
Two pools, two _components_, as many members as you want. Am I missing something?

**Comment by WireWhiz** [comment] 2022-06-14 19:23
In my current implementation, VirtualType and ComponentDescritption don't actually store the type, just info about its size and construct/desctruct/copy/move operations. They're passed off to my equivalent of a pool and all the data is stored contiguously in chunks/pages using the ComponentDescritption to know how to interact with the data. If possible I would like to keep the data stored contiguously instead of referencing each member with pointers.

**Comment by skypjack** [comment] 2022-06-16 06:05
I think I'm missing something, sorry. You've said that your _types_ are not actual C++ type. Instead, they are maps of _fake_ members (literally pointers to `VirtualType`). Then you said that these _types_ and descriptors are just metadata for existing C++ types.
I'd love to help you and provide you with a way to do what you're trying to achieve, but I'm pretty confused at the moment.

**Comment by WireWhiz** [comment] 2022-06-16 20:26
> If I understand correctly, your _types_ are not actual C++ types. Instead, they are maps of _real_ C++ members _described by_ pointers to `VirtualType`. Both the `VirtualType` and the (`ComponentDefinition`/ComponentDescritption) descriptors are just metadata for existing C++ types, and are _not_ stored in any pool or other thing. However, `struct` instances built using a ComponentDescritption _are_ stored in pools and assigned to actual entity identifiers.

Yep, that is exactly what I'm doing.

**Comment by skypjack** [comment] 2022-06-18 13:40
Ahaaaa ok, so what you want is to store ie all `VirtualVariable<bool>` tightly packed somewhere, then all `VirtualVariable<float>` all tightly packed somewhere else and so on? Or the other way around, that is, all _members_ of a single objects tightly packed, then all members of the next object and so on?

**Comment by WireWhiz** [comment] 2022-06-20 06:18
Currently, in my own code, I use the second method and have all the members of an object packed together. Would it make more sense for performance to do it the other way?

**Comment by skypjack** [comment] 2022-06-21 07:05
You don't have them packed together if you create them using `std::make_unique`. You've all the pointers to the base class packed together instead. However, every time you try to access a component, you jump somewhere in memory.

**Comment by WireWhiz** [comment] 2022-06-21 07:24
Only the metadata for the types was created with std::make_unique, and I've since refactored it so that I pass in an array of enums representing the types I want as members to ComponentDescriptions. When actually storing objects described by said description I use a switch statement to find the right constructor for each member and 'new(void*) T' to emplace the type in a paged array of bytes that's used for the actual storage of the components. I do a similar thing for move/copy/destruct operations between archetypes (as my current system is archetypal)

**Comment by WireWhiz** [comment] 2022-06-21 07:27
The main question I have is if I could quickly set up a system like this or better in Entt, as it would probably be better for performance. Or if I should continue extending my own system.

**Comment by codylico** [comment] 2022-06-21 15:07
To clarify, the `VirtualVariable<T>` is metadata meant to help describe the component; the `VirtualVariable<T>` not store anything, which is _why_ you were able to replace it with an enumeration. Do I understand correctly?

I wonder if `VirtualVariable<T>` and `ComponentDescription` are trying to do something similar to `meta_type`....

**Comment by WireWhiz** [comment] 2022-06-21 15:14
Yes, VirtualVariable did not store anything. It was a template that allowed me to access the constructor/destructor/copy/move functions of types through virtual functions.

**Comment by skypjack** [comment] 2022-06-22 06:58
> I wonder if VirtualVariable<T> and ComponentDescription are trying to do something similar to meta_type....

@codylico I wouldn't say so, mostly because his types aren't backed by actual C++ types (we agreed on this, right? 😅).

> The main question I have is if I could quickly set up a system like this or better in Entt, as it would probably be better for performance. Or if I should continue extending my own system.

It's your call. I can't tell you to go a way or the other.

The way you've implemented it triggers a lot of jumps in memory, literally one for every member you want to access.
You can likely do better but it really depends on your access patterns. For example, if you want to elaborate a single object at a time and therefore all its members at once, the tradeoff is probably between performance and memory usage. That is, you can store them in a buffer that is large enough to store the largest basic type (or most of them at least, like an `entt::any` with a proper size). This way, you can highly reduce the number of jumps by paying the price in terms of memory usage.
Take this with a grain of salt though, I'm just throwing at you my first thoughts.

**Comment by skypjack** [comment] 2022-06-29 05:49
The issue is starving. I assume it was answered though. I'll close it in a couple of days if no other comments show up. Thanks.

**Closed** 2022-07-03 10:04 UTC
Labels: question, solved
