### ISSUE TITLE
Bug in Emitter class

### ISSUE THREAD

**Issue by gamagan** [skypjack/entt#123] opened 2018-08-09 00:51 UTC
I ran into this issue, on Windows 10, in my codebase, which goes something like this:

- The main exe loads a dll dynamically. There is an emitter instance in the exe.
- The dll registers for event with the emitter class using Emitter.on() method.
- ...
- The main exe prepares to unload the dll.
- Prior to unloading, the dll unregisters the event using Emitter.erase() method.
- The dll is unloaded by the main exe.
- Upon exit, the program will crash.

The problem is that erase() does not reset() the unique_ptr that holds the handler object. When the program exits, it tries to remove that memory. I don't quite understand how it happens, but it seems the memory is associated with the dll that was unloaded and, at that point, is no longer valid.

Unfortunately for me, I found this problem while making a huge change to my codebase, so it took me all day to figure out, because I thought it was my code.

The following change fixes the problem.

    template<typename Event>
    void erase(Connection<Event> conn) ENTT_NOEXCEPT {
        handler<Event>().erase(std::move(conn));
        nullify<Event>();         // <---- Add this to erase().
    }

    template<typename Event>
    void nullify() ENTT_NOEXCEPT {
        const std::size_t family = handler_family::type<Event>();

        if (family < handlers.size()) {
            handlers[family].reset();
        }
    }

**Comment by gamagan** [comment] 2018-08-09 02:30
The change that I posted above does not work well. Specifically, it will cause problems if 2 clients connect to the same event and both try to erase the connection. The second one will core.

**Comment by skypjack** [comment] 2018-08-09 06:44
>Unfortunately for me, I found this problem while making a huge change to my codebase, so it took me all day to figure out, because I thought it was my code.

I'm sorry, the bad news is that it was your code actually. This is a duplicate of #111 and #113 and would be solved by what has been discussed with #114 (yet to implement).  
The emitter class, as well as the dispatcher and the registry, completely relies on type erasure and performs dynamic allocations under the hood to accommodate pools/wrappers for the given types. When you attach the listener within the DLL, a proper wrapper for the type of event doesn't exist yet and therefore it's created. Unfortunately, the memory is allocated across boundaries and it's released when you unload the DLL. However, the emitter is instantiated on the other side of the boundary and when it's destroyed it tries to release its memory. However, that memory is no longer owned by the process and it causes the crash.

The straightforward approach to solve it is probably to allow mixed compile-time/runtime classes and to introduce custom allocators (see the issues above mentioned). The good news is that a solution exists and `EnTT` is going towards it at least. In fact, both the things are in the backlog (TODO file) but I've not enough bandwidth to work on them right now (and I'm pretty sure you don't want to hire me to give them high priority, as it happened in the past for some other features).  
They will be implemented sooner or later, but you have to find a workaround in the meantime as other users did.

I invite you to join the gitter chat (see the badge in the README file) if you want to go further with the discussion.

**Closed by skypjack** 2018-08-09 06:44 UTC
Labels: duplicate, invalid

**Comment by gamagan** [comment] 2018-08-09 22:56
Thanks for replying.

If this issue has been reported before, and you're thinking up a solution for it, then this is obviously a problem. You shouldn't close the ticket because the problem hasn't been fixed. This would help others that might run into this same issue. The tickets that you mentioned could have saved me precious hours yesterday, for example. But, when I went look, there were no opened issues, so I missed it.

If the problem is only with the Family id being static then, for my personal code, I could probably fix my issue by making the event classes expose a static constexpr id method that returns a unique number.

**Comment by skypjack** [comment] 2018-08-10 15:12
Hold back your horses.  
Put aside the fact that there is an useful search bar to look for issues by arguments, I'm not saying there is a problem anyway.

`EnTT` hasn't been designed with shared libraries in mind and it's tricky to make it work, but it's possible. The issues I linked discuss facilities to help users to use this library in such a case, mainly because today it requires a knowledge that is sometimes beyond the one of the game dev.  
However, all of the features have (apparently) nothing to do with shared libraries: custom allocators, mixed compile-time/runtime tools, etc. All of them are also in the backlog from a lot of time, far before anyone even mentioned shared libraries at all.

I renew my invite to join the gitter chat if you have problems with shared libraries. There are people much more skilled than me that can help you. ;-)
