### ISSUE TITLE
ECS visit issue. Members not defined?

### ISSUE THREAD

**Issue by anthofoxo** [skypjack/entt#696] opened 2021-04-26 01:03 UTC
I'm trying to copy all stuff from one registry to anther and in the documentation this example claims to do exactly this. 

`
registry.visit([&](const auto info)
{
	auto storage = registry.storage(info);
	other.storage(info)->insert(other, storage->data(), storage->raw(), storage->size());
});`

Both other and registry are entt::registry&

When using visual studio. I get some errors saying. data, insert, raw, size and __this is not a member of entt::Storage<>

I'm including all the entt headers too so I shouldn't be missing anything

![image](https://user-images.githubusercontent.com/17318787/116016086-8a4ab380-a609-11eb-95f0-d58dbc6aac23.png)

![image](https://user-images.githubusercontent.com/17318787/116016185-e44b7900-a609-11eb-87ad-3db7a9eaa662.png)

I pulled the latest i can off of git here and entt::storage seems to be defined correctly. So I don't know if I'm doing something wrong here or if there's just a newer way to do it.

Edit: Solution for msvc
Old: https://godbolt.org/z/h4q9o1ecj
New: https://godbolt.org/z/8jccbE4vb

Thanks for @cmartel for posting a solution to this

**Comment by skypjack** [comment] 2021-04-26 07:40
Hi, I guess [this](https://github.com/skypjack/entt/issues/694#issuecomment-823996781) and [this](https://github.com/skypjack/entt/discussions/684#discussion-3299774) can help with the issue. 🙂 
Let me know if you've any other doubt.

**Comment by anthofoxo** [comment] 2021-04-26 16:40
I've followed some of these links and tried implementing this copying using some other methods. It always comes back down to this issue, Unable to find functions, unable to deduce templates etc. I'd really like a way to do this without having to manually write a cast for every component I make

**Comment by skypjack** [comment] 2021-04-26 20:17
The discussion above contains a link to a working example on godbolt.
You don't have to manually write a cast for every component.

**Comment by anthofoxo** [comment] 2021-04-26 21:58
Ive used that to try getting it working, i cant figure out that the issue im having even is. When i translate that into msvc i get these compiler errors now. 
![image](https://user-images.githubusercontent.com/17318787/116155962-dbfe4700-a6b8-11eb-85a4-e2ddf126ec3d.png)

This should be exactly the same as on that example but i still get compiler issues.

![image](https://user-images.githubusercontent.com/17318787/116156017-eddfea00-a6b8-11eb-846a-b05547937afd.png)


So im at a loss on how to even approach fixing that

**Comment by skypjack** [comment] 2021-04-27 07:06
Unfortunately, it's hard to investigate a compilation error without looking at your code.
Can you post a minimal example [here](https://godbolt.org/z/5z6Pvarz8)? I'd be glad to look into it and tell you what's wrong.

**Comment by anthofoxo** [comment] 2021-04-27 21:52
So i took the exact example from the link in that example here.
https://godbolt.org/z/h4q9o1ecj
And i stuck into my visual studio setup and i get those same errors. I cant really give a godbolt link since it seems its vs compiler doesnt give the entt library for an option

**Comment by skypjack** [comment] 2021-04-27 22:14
Do you have the `/permissive` flag set?

**Comment by anthofoxo** [comment] 2021-04-27 22:53
I did not. I tried without it on with /permissive and /permissive- and with combination of /std:c++17 and /std:c++latest
None of these combinations made any difference. Any other flags i should try out?

**Comment by Innokentiy-Alaytsev** [comment] 2021-04-28 06:53
> 
> 
> Ive used that to try getting it working, i cant figure out that the issue im having even is. When i translate that into msvc i get these compiler errors now.
> ![image](https://user-images.githubusercontent.com/17318787/116155962-dbfe4700-a6b8-11eb-85a4-e2ddf126ec3d.png)
> 
> This should be exactly the same as on that example but i still get compiler issues.
> 
> ![image](https://user-images.githubusercontent.com/17318787/116156017-eddfea00-a6b8-11eb-846a-b05547937afd.png)
> 
> So im at a loss on how to even approach fixing that

Could you provide a full error message from the "Output" tab? It contains way more information than "Errors" tab output, namely information about the location of the problem.

**Comment by anthofoxo** [comment] 2021-04-30 02:40
I totally can. the source is the exact example just in msvc. The output tab gives me this output

Build started...
EnttTest.cpp(30,27): error C3535: cannot deduce type for 'auto' from 'overloaded-function'
EnttTest.cpp(32): message : see reference to class template instantiation 'PolyStorage<Entity>' being compiled
EnttTest.cpp(31,1): error C2975: 'Value': invalid template argument for 'entt::value_list', expected compile-time constant expression
vendor\entt\src\entt\core\type_traits.hpp(322): message : see declaration of 'Value'

**Comment by Innokentiy-Alaytsev** [comment] 2021-04-30 05:35
Use `entt::overload` and disambiguate some function registration. I'm from movile, but later I'll look into it from PC.

**Comment by skypjack** [comment] 2021-04-30 06:37
Ah @Innokentiy-Alaytsev is right, this error is telling us that the compiler cannot disambiguate an overload:
> cannot deduce type for 'auto' from 'overloaded-function'

Good catch. @anthofoxo can you post the storage definition? Not necessarily in a working example, but at least we can try to figure out what function is giving you problems.

**Comment by anthofoxo** [comment] 2021-04-30 06:40
I'm on mobile rn. But the entt code itself is latest from master. The example is literally this. https://godbolt.org/z/h4q9o1ecj

Just put into visual studio. I'll look into more details tomorrow and try entt::overload when I'm free

**Comment by cmartel** [comment] 2021-05-01 01:17
I can maybe help disambiguate these errors a little, as I've been bashing my head against essentially the same ones.

> I'm including all the entt headers too so I shouldn't be missing anything
> 
> ![image](https://user-images.githubusercontent.com/17318787/116016086-8a4ab380-a609-11eb-95f0-d58dbc6aac23.png)

Out of curiosity, @anthofoxo, when you say you're including all headers, are you doing this through a precompiled header file?

I'm using entt in an UE4 project, which is including `<entt/entt.hpp>` directly in its project precompiled header. I've also used the copy_to godbolt example as a starting point. The above error occurs from the compiler not seeing the type trait for the PolyStorage definition. Ripping out entt from the precompiled header and manually including it within the file I'm trying to define a poly storage in fixes that problem.

I suspect that if the entt registry is added to PCH without having the storage type trait visible, then it doesn't matter if it's visible in the translation unit. I'm not sure whether the problem here stems from the precompilation part or from the include order yielded by the precompiled header.

In the course of experimenting, I've also seen the second "cannot deduce type" compilation error, I'll try to see if I can get it to happen again.

**Comment by anthofoxo** [comment] 2021-05-01 03:12
I'm not using any pch for the test. I've tried just including registry. Poly storage. The entire ent via entt/entt.hpp the includes I do doesn't make a difference for me @cmartel

**Comment by cmartel** [comment] 2021-05-01 04:14
Okay, here's as far as I could get with my investigations.

For the "cannot deduce type for auto", try this variant of the `copy_to` example where the function is moved in struct scope: https://godbolt.org/z/8jccbE4vb If I compile that under VS2019, it fixes the disambiguation problem. It also works correctly, without the first error.

Then, if you uncomment that first `entt:registry hello;` line, it'll cause the same error:
`1>Main.cpp(59,33): error C2039: 'copy_to': is not a member of 'entt::Storage<Entity>::type<entt::poly_base<entt::poly<entt::Storage<Entity>>>>'`

Note that this also happens under clang in the godbolt case.

I believe my initial premise that having the type trait specialization in the same translation unit is not sufficient: it also must appear before the first _usage_ of the type trait. Just defining an `entt::registry` is sufficient to instantiate the type trait and pull the default entt::Storage implementation. In my particular case, the PCH did contain the "master" class that holds a registry by value, thus triggering usage of the wrong type trait. Is this what's happening in your original case?

Then, I guess a more specific static polymorphism question for skypjack: Based on my experiments on this, am I correctly deducing that the poly storage is baked into the registry by the first type trait it encounters, and then its static vtable will point to those functions even if different compile units define different poly storage types? (i.e.: you can only ever have one set of static poly functions for the entire lifetime of a registry)

**Comment by skypjack** [comment] 2021-05-01 08:34
> it also must appear before the first usage of the type trait

I dare to say that this isn't due to EnTT, it's how C++ works. You're specializing a class template (`poly_storage_traits`). If that specialization isn't visible (and it is not at line 5 of your example), it cannot be used.
Defining something **after** first use is definitely a way to make it not visible. 🙂 

> you can only ever have one set of static poly functions for the entire lifetime of a registry

Yeah. Are you suggesting that a dynamic model with which we can change how a type is copied at runtime would be useful?

**Comment by cmartel** [comment] 2021-05-01 22:09
> I dare to say that this isn't due to EnTT, it's how C++ works.
Oh, you're absolutely right! But as I mentioned, I've only dealt with basic usages of type traits (mainly overload resolution). That usage made it seem like having a type trait defined is sufficient, when it probably just wasn't nearly as likely to be defined after its usage. Whereas this particular case happens as soon as a registry is defined so much more likely to trip. :)

> Are you suggesting that a dynamic model with which we can change how a type is copied at runtime would be useful?
Not currently, no--I was mainly trying to confirm my understanding of the poly storage. I wasn't certain if the functionality thus added was "free floating" or tied to the registry. I've since confirmed it's the latter, so I'll centralise the different uses of visit/poly_storage instead of trying to organise them into separate files.

I don't want to keep hijacking this thread, but hopefully this discussion might've helped anthofoxo figure out their problem.

**Comment by anthofoxo** [comment] 2021-05-07 18:02
@cmartel the godbolt link from the discussion earlier does indeed fix this for me https://godbolt.org/z/8jccbE4vb
So ill get that in my codebase and see if any other issues arise from it. I'm unsure if this should be closed or whatnot. I'm updating the original post with the working example for msvc

**Comment by skypjack** [comment] 2021-05-08 15:09
I feel like we can safely close this one, mainly because I still don't get what the problem was and how to reproduce it.
Feel free to reopen the issue at any time if you can pack a reproducible example that helps to track it down eventually.
And thanks to @cmartel for helping!! 🙂

**Closed by skypjack** 2021-05-08 15:09 UTC
Labels: duplicate
